/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Client;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientRecord extends UpdatableRecordImpl<ClientRecord> implements Record3<String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.client.fullname</code>.
     */
    public void setFullname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.client.fullname</code>.
     */
    public String getFullname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sales.client.clientid</code>.
     */
    public void setClientid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.client.clientid</code>.
     */
    public Integer getClientid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.client.number</code>.
     */
    public void setNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.client.number</code>.
     */
    public String getNumber() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Client.CLIENT.FULLNAME;
    }

    @Override
    public Field<Integer> field2() {
        return Client.CLIENT.CLIENTID;
    }

    @Override
    public Field<String> field3() {
        return Client.CLIENT.NUMBER;
    }

    @Override
    public String component1() {
        return getFullname();
    }

    @Override
    public Integer component2() {
        return getClientid();
    }

    @Override
    public String component3() {
        return getNumber();
    }

    @Override
    public String value1() {
        return getFullname();
    }

    @Override
    public Integer value2() {
        return getClientid();
    }

    @Override
    public String value3() {
        return getNumber();
    }

    @Override
    public ClientRecord value1(String value) {
        setFullname(value);
        return this;
    }

    @Override
    public ClientRecord value2(Integer value) {
        setClientid(value);
        return this;
    }

    @Override
    public ClientRecord value3(String value) {
        setNumber(value);
        return this;
    }

    @Override
    public ClientRecord values(String value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRecord
     */
    public ClientRecord() {
        super(Client.CLIENT);
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(String fullname, Integer clientid, String number) {
        super(Client.CLIENT);

        setFullname(fullname);
        setClientid(clientid);
        setNumber(number);
        resetChangedOnNotNull();
    }
}
