/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Client;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientRecord extends UpdatableRecordImpl<ClientRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.client.clientid</code>.
     */
    public void setClientid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.client.clientid</code>.
     */
    public Integer getClientid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.client.fullname</code>.
     */
    public void setFullname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.client.fullname</code>.
     */
    public String getFullname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Client.CLIENT.CLIENTID;
    }

    @Override
    public Field<String> field2() {
        return Client.CLIENT.FULLNAME;
    }

    @Override
    public Integer component1() {
        return getClientid();
    }

    @Override
    public String component2() {
        return getFullname();
    }

    @Override
    public Integer value1() {
        return getClientid();
    }

    @Override
    public String value2() {
        return getFullname();
    }

    @Override
    public ClientRecord value1(Integer value) {
        setClientid(value);
        return this;
    }

    @Override
    public ClientRecord value2(String value) {
        setFullname(value);
        return this;
    }

    @Override
    public ClientRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientRecord
     */
    public ClientRecord() {
        super(Client.CLIENT);
    }

    /**
     * Create a detached, initialised ClientRecord
     */
    public ClientRecord(Integer clientid, String fullname) {
        super(Client.CLIENT);

        setClientid(clientid);
        setFullname(fullname);
        resetChangedOnNotNull();
    }
}
