/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Clientdish;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientdishRecord extends UpdatableRecordImpl<ClientdishRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.clientdish.dishid</code>.
     */
    public void setDishid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.clientdish.dishid</code>.
     */
    public Integer getDishid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.clientdish.clientid</code>.
     */
    public void setClientid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.clientdish.clientid</code>.
     */
    public Integer getClientid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.clientdish.dishname</code>.
     */
    public void setDishname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.clientdish.dishname</code>.
     */
    public String getDishname() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Clientdish.CLIENTDISH.DISHID;
    }

    @Override
    public Field<Integer> field2() {
        return Clientdish.CLIENTDISH.CLIENTID;
    }

    @Override
    public Field<String> field3() {
        return Clientdish.CLIENTDISH.DISHNAME;
    }

    @Override
    public Integer component1() {
        return getDishid();
    }

    @Override
    public Integer component2() {
        return getClientid();
    }

    @Override
    public String component3() {
        return getDishname();
    }

    @Override
    public Integer value1() {
        return getDishid();
    }

    @Override
    public Integer value2() {
        return getClientid();
    }

    @Override
    public String value3() {
        return getDishname();
    }

    @Override
    public ClientdishRecord value1(Integer value) {
        setDishid(value);
        return this;
    }

    @Override
    public ClientdishRecord value2(Integer value) {
        setClientid(value);
        return this;
    }

    @Override
    public ClientdishRecord value3(String value) {
        setDishname(value);
        return this;
    }

    @Override
    public ClientdishRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientdishRecord
     */
    public ClientdishRecord() {
        super(Clientdish.CLIENTDISH);
    }

    /**
     * Create a detached, initialised ClientdishRecord
     */
    public ClientdishRecord(Integer dishid, Integer clientid, String dishname) {
        super(Clientdish.CLIENTDISH);

        setDishid(dishid);
        setClientid(clientid);
        setDishname(dishname);
        resetChangedOnNotNull();
    }
}
