/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDate;

import jooqdata.tables.Clientduty;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientdutyRecord extends TableRecordImpl<ClientdutyRecord> implements Record5<Long, String, String, Double, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.clientduty.clientid</code>.
     */
    public void setClientid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.clientduty.clientid</code>.
     */
    public Long getClientid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sales.clientduty.clientname</code>.
     */
    public void setClientname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.clientduty.clientname</code>.
     */
    public String getClientname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sales.clientduty.number</code>.
     */
    public void setNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.clientduty.number</code>.
     */
    public String getNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sales.clientduty.duty</code>.
     */
    public void setDuty(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.clientduty.duty</code>.
     */
    public Double getDuty() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>sales.clientduty.data</code>.
     */
    public void setData(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.clientduty.data</code>.
     */
    public LocalDate getData() {
        return (LocalDate) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, Double, LocalDate> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, Double, LocalDate> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Clientduty.CLIENTDUTY.CLIENTID;
    }

    @Override
    public Field<String> field2() {
        return Clientduty.CLIENTDUTY.CLIENTNAME;
    }

    @Override
    public Field<String> field3() {
        return Clientduty.CLIENTDUTY.NUMBER;
    }

    @Override
    public Field<Double> field4() {
        return Clientduty.CLIENTDUTY.DUTY;
    }

    @Override
    public Field<LocalDate> field5() {
        return Clientduty.CLIENTDUTY.DATA;
    }

    @Override
    public Long component1() {
        return getClientid();
    }

    @Override
    public String component2() {
        return getClientname();
    }

    @Override
    public String component3() {
        return getNumber();
    }

    @Override
    public Double component4() {
        return getDuty();
    }

    @Override
    public LocalDate component5() {
        return getData();
    }

    @Override
    public Long value1() {
        return getClientid();
    }

    @Override
    public String value2() {
        return getClientname();
    }

    @Override
    public String value3() {
        return getNumber();
    }

    @Override
    public Double value4() {
        return getDuty();
    }

    @Override
    public LocalDate value5() {
        return getData();
    }

    @Override
    public ClientdutyRecord value1(Long value) {
        setClientid(value);
        return this;
    }

    @Override
    public ClientdutyRecord value2(String value) {
        setClientname(value);
        return this;
    }

    @Override
    public ClientdutyRecord value3(String value) {
        setNumber(value);
        return this;
    }

    @Override
    public ClientdutyRecord value4(Double value) {
        setDuty(value);
        return this;
    }

    @Override
    public ClientdutyRecord value5(LocalDate value) {
        setData(value);
        return this;
    }

    @Override
    public ClientdutyRecord values(Long value1, String value2, String value3, Double value4, LocalDate value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientdutyRecord
     */
    public ClientdutyRecord() {
        super(Clientduty.CLIENTDUTY);
    }

    /**
     * Create a detached, initialised ClientdutyRecord
     */
    public ClientdutyRecord(Long clientid, String clientname, String number, Double duty, LocalDate data) {
        super(Clientduty.CLIENTDUTY);

        setClientid(clientid);
        setClientname(clientname);
        setNumber(number);
        setDuty(duty);
        setData(data);
        resetChangedOnNotNull();
    }
}
