/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.math.BigDecimal;
import java.time.LocalDate;

import jooqdata.tables.Consignmentnote;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConsignmentnoteRecord extends UpdatableRecordImpl<ConsignmentnoteRecord> implements Record4<Integer, Integer, BigDecimal, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.consignmentnote.consignmentid</code>.
     */
    public void setConsignmentid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.consignmentnote.consignmentid</code>.
     */
    public Integer getConsignmentid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.consignmentnote.supplierid</code>.
     */
    public void setSupplierid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.consignmentnote.supplierid</code>.
     */
    public Integer getSupplierid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.consignmentnote.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.consignmentnote.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>sales.consignmentnote.date</code>.
     */
    public void setDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.consignmentnote.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, BigDecimal, LocalDate> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, BigDecimal, LocalDate> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Consignmentnote.CONSIGNMENTNOTE.CONSIGNMENTID;
    }

    @Override
    public Field<Integer> field2() {
        return Consignmentnote.CONSIGNMENTNOTE.SUPPLIERID;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Consignmentnote.CONSIGNMENTNOTE.AMOUNT;
    }

    @Override
    public Field<LocalDate> field4() {
        return Consignmentnote.CONSIGNMENTNOTE.DATE;
    }

    @Override
    public Integer component1() {
        return getConsignmentid();
    }

    @Override
    public Integer component2() {
        return getSupplierid();
    }

    @Override
    public BigDecimal component3() {
        return getAmount();
    }

    @Override
    public LocalDate component4() {
        return getDate();
    }

    @Override
    public Integer value1() {
        return getConsignmentid();
    }

    @Override
    public Integer value2() {
        return getSupplierid();
    }

    @Override
    public BigDecimal value3() {
        return getAmount();
    }

    @Override
    public LocalDate value4() {
        return getDate();
    }

    @Override
    public ConsignmentnoteRecord value1(Integer value) {
        setConsignmentid(value);
        return this;
    }

    @Override
    public ConsignmentnoteRecord value2(Integer value) {
        setSupplierid(value);
        return this;
    }

    @Override
    public ConsignmentnoteRecord value3(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public ConsignmentnoteRecord value4(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public ConsignmentnoteRecord values(Integer value1, Integer value2, BigDecimal value3, LocalDate value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConsignmentnoteRecord
     */
    public ConsignmentnoteRecord() {
        super(Consignmentnote.CONSIGNMENTNOTE);
    }

    /**
     * Create a detached, initialised ConsignmentnoteRecord
     */
    public ConsignmentnoteRecord(Integer consignmentid, Integer supplierid, BigDecimal amount, LocalDate date) {
        super(Consignmentnote.CONSIGNMENTNOTE);

        setConsignmentid(consignmentid);
        setSupplierid(supplierid);
        setAmount(amount);
        setDate(date);
        resetChangedOnNotNull();
    }
}
