/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.math.BigDecimal;

import jooqdata.tables.Consproduct;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConsproductRecord extends TableRecordImpl<ConsproductRecord> implements Record3<Integer, Integer, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.consproduct.consignmentid</code>.
     */
    public void setConsignmentid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.consproduct.consignmentid</code>.
     */
    public Integer getConsignmentid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.consproduct.productid</code>.
     */
    public void setProductid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.consproduct.productid</code>.
     */
    public Integer getProductid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.consproduct.gross</code>.
     */
    public void setGross(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.consproduct.gross</code>.
     */
    public BigDecimal getGross() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, BigDecimal> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, BigDecimal> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Consproduct.CONSPRODUCT.CONSIGNMENTID;
    }

    @Override
    public Field<Integer> field2() {
        return Consproduct.CONSPRODUCT.PRODUCTID;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Consproduct.CONSPRODUCT.GROSS;
    }

    @Override
    public Integer component1() {
        return getConsignmentid();
    }

    @Override
    public Integer component2() {
        return getProductid();
    }

    @Override
    public BigDecimal component3() {
        return getGross();
    }

    @Override
    public Integer value1() {
        return getConsignmentid();
    }

    @Override
    public Integer value2() {
        return getProductid();
    }

    @Override
    public BigDecimal value3() {
        return getGross();
    }

    @Override
    public ConsproductRecord value1(Integer value) {
        setConsignmentid(value);
        return this;
    }

    @Override
    public ConsproductRecord value2(Integer value) {
        setProductid(value);
        return this;
    }

    @Override
    public ConsproductRecord value3(BigDecimal value) {
        setGross(value);
        return this;
    }

    @Override
    public ConsproductRecord values(Integer value1, Integer value2, BigDecimal value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConsproductRecord
     */
    public ConsproductRecord() {
        super(Consproduct.CONSPRODUCT);
    }

    /**
     * Create a detached, initialised ConsproductRecord
     */
    public ConsproductRecord(Integer consignmentid, Integer productid, BigDecimal gross) {
        super(Consproduct.CONSPRODUCT);

        setConsignmentid(consignmentid);
        setProductid(productid);
        setGross(gross);
        resetChangedOnNotNull();
    }
}
