/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Consproduct;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConsproductRecord extends UpdatableRecordImpl<ConsproductRecord> implements Record5<Integer, Integer, Double, Double, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.consproduct.consignmentid</code>.
     */
    public void setConsignmentid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.consproduct.consignmentid</code>.
     */
    public Integer getConsignmentid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.consproduct.productid</code>.
     */
    public void setProductid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.consproduct.productid</code>.
     */
    public Integer getProductid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.consproduct.gross</code>.
     */
    public void setGross(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.consproduct.gross</code>.
     */
    public Double getGross() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>sales.consproduct.quantity</code>.
     */
    public void setQuantity(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.consproduct.quantity</code>.
     */
    public Double getQuantity() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>sales.consproduct.consproductid</code>.
     */
    public void setConsproductid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.consproduct.consproductid</code>.
     */
    public Integer getConsproductid() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Double, Double, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Double, Double, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Consproduct.CONSPRODUCT.CONSIGNMENTID;
    }

    @Override
    public Field<Integer> field2() {
        return Consproduct.CONSPRODUCT.PRODUCTID;
    }

    @Override
    public Field<Double> field3() {
        return Consproduct.CONSPRODUCT.GROSS;
    }

    @Override
    public Field<Double> field4() {
        return Consproduct.CONSPRODUCT.QUANTITY;
    }

    @Override
    public Field<Integer> field5() {
        return Consproduct.CONSPRODUCT.CONSPRODUCTID;
    }

    @Override
    public Integer component1() {
        return getConsignmentid();
    }

    @Override
    public Integer component2() {
        return getProductid();
    }

    @Override
    public Double component3() {
        return getGross();
    }

    @Override
    public Double component4() {
        return getQuantity();
    }

    @Override
    public Integer component5() {
        return getConsproductid();
    }

    @Override
    public Integer value1() {
        return getConsignmentid();
    }

    @Override
    public Integer value2() {
        return getProductid();
    }

    @Override
    public Double value3() {
        return getGross();
    }

    @Override
    public Double value4() {
        return getQuantity();
    }

    @Override
    public Integer value5() {
        return getConsproductid();
    }

    @Override
    public ConsproductRecord value1(Integer value) {
        setConsignmentid(value);
        return this;
    }

    @Override
    public ConsproductRecord value2(Integer value) {
        setProductid(value);
        return this;
    }

    @Override
    public ConsproductRecord value3(Double value) {
        setGross(value);
        return this;
    }

    @Override
    public ConsproductRecord value4(Double value) {
        setQuantity(value);
        return this;
    }

    @Override
    public ConsproductRecord value5(Integer value) {
        setConsproductid(value);
        return this;
    }

    @Override
    public ConsproductRecord values(Integer value1, Integer value2, Double value3, Double value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConsproductRecord
     */
    public ConsproductRecord() {
        super(Consproduct.CONSPRODUCT);
    }

    /**
     * Create a detached, initialised ConsproductRecord
     */
    public ConsproductRecord(Integer consignmentid, Integer productid, Double gross, Double quantity, Integer consproductid) {
        super(Consproduct.CONSPRODUCT);

        setConsignmentid(consignmentid);
        setProductid(productid);
        setGross(gross);
        setQuantity(quantity);
        setConsproductid(consproductid);
        resetChangedOnNotNull();
    }
}
