/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDate;

import jooqdata.tables.Consignmentnote;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConsignmentnoteRecord extends UpdatableRecordImpl<ConsignmentnoteRecord> implements Record4<Integer, Double, LocalDate, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.consignmentnote.supplierid</code>.
     */
    public void setSupplierid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.consignmentnote.supplierid</code>.
     */
    public Integer getSupplierid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.consignmentnote.amount</code>.
     */
    public void setAmount(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.consignmentnote.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>sales.consignmentnote.date</code>.
     */
    public void setDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.consignmentnote.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>sales.consignmentnote.consignmentid</code>.
     */
    public void setConsignmentid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.consignmentnote.consignmentid</code>.
     */
    public Integer getConsignmentid() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Double, LocalDate, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Double, LocalDate, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Consignmentnote.CONSIGNMENTNOTE.SUPPLIERID;
    }

    @Override
    public Field<Double> field2() {
        return Consignmentnote.CONSIGNMENTNOTE.AMOUNT;
    }

    @Override
    public Field<LocalDate> field3() {
        return Consignmentnote.CONSIGNMENTNOTE.DATE;
    }

    @Override
    public Field<Integer> field4() {
        return Consignmentnote.CONSIGNMENTNOTE.CONSIGNMENTID;
    }

    @Override
    public Integer component1() {
        return getSupplierid();
    }

    @Override
    public Double component2() {
        return getAmount();
    }

    @Override
    public LocalDate component3() {
        return getDate();
    }

    @Override
    public Integer component4() {
        return getConsignmentid();
    }

    @Override
    public Integer value1() {
        return getSupplierid();
    }

    @Override
    public Double value2() {
        return getAmount();
    }

    @Override
    public LocalDate value3() {
        return getDate();
    }

    @Override
    public Integer value4() {
        return getConsignmentid();
    }

    @Override
    public ConsignmentnoteRecord value1(Integer value) {
        setSupplierid(value);
        return this;
    }

    @Override
    public ConsignmentnoteRecord value2(Double value) {
        setAmount(value);
        return this;
    }

    @Override
    public ConsignmentnoteRecord value3(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public ConsignmentnoteRecord value4(Integer value) {
        setConsignmentid(value);
        return this;
    }

    @Override
    public ConsignmentnoteRecord values(Integer value1, Double value2, LocalDate value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConsignmentnoteRecord
     */
    public ConsignmentnoteRecord() {
        super(Consignmentnote.CONSIGNMENTNOTE);
    }

    /**
     * Create a detached, initialised ConsignmentnoteRecord
     */
    public ConsignmentnoteRecord(Integer supplierid, Double amount, LocalDate date, Integer consignmentid) {
        super(Consignmentnote.CONSIGNMENTNOTE);

        setSupplierid(supplierid);
        setAmount(amount);
        setDate(date);
        setConsignmentid(consignmentid);
        resetChangedOnNotNull();
    }
}
