/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Dish;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DishRecord extends UpdatableRecordImpl<DishRecord> implements Record7<String, Double, Double, Double, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.dish.dishname</code>.
     */
    public void setDishname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.dish.dishname</code>.
     */
    public String getDishname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sales.dish.weight</code>.
     */
    public void setWeight(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.dish.weight</code>.
     */
    public Double getWeight() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>sales.dish.firstcost</code>.
     */
    public void setFirstcost(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.dish.firstcost</code>.
     */
    public Double getFirstcost() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>sales.dish.price</code>.
     */
    public void setPrice(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.dish.price</code>.
     */
    public Double getPrice() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>sales.dish.techproductid</code>.
     */
    public void setTechproductid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.dish.techproductid</code>.
     */
    public Integer getTechproductid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sales.dish.dishid</code>.
     */
    public void setDishid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>sales.dish.dishid</code>.
     */
    public Integer getDishid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>sales.dish.category</code>.
     */
    public void setCategory(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sales.dish.category</code>.
     */
    public String getCategory() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, Double, Double, Double, Integer, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, Double, Double, Double, Integer, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Dish.DISH.DISHNAME;
    }

    @Override
    public Field<Double> field2() {
        return Dish.DISH.WEIGHT;
    }

    @Override
    public Field<Double> field3() {
        return Dish.DISH.FIRSTCOST;
    }

    @Override
    public Field<Double> field4() {
        return Dish.DISH.PRICE;
    }

    @Override
    public Field<Integer> field5() {
        return Dish.DISH.TECHPRODUCTID;
    }

    @Override
    public Field<Integer> field6() {
        return Dish.DISH.DISHID;
    }

    @Override
    public Field<String> field7() {
        return Dish.DISH.CATEGORY;
    }

    @Override
    public String component1() {
        return getDishname();
    }

    @Override
    public Double component2() {
        return getWeight();
    }

    @Override
    public Double component3() {
        return getFirstcost();
    }

    @Override
    public Double component4() {
        return getPrice();
    }

    @Override
    public Integer component5() {
        return getTechproductid();
    }

    @Override
    public Integer component6() {
        return getDishid();
    }

    @Override
    public String component7() {
        return getCategory();
    }

    @Override
    public String value1() {
        return getDishname();
    }

    @Override
    public Double value2() {
        return getWeight();
    }

    @Override
    public Double value3() {
        return getFirstcost();
    }

    @Override
    public Double value4() {
        return getPrice();
    }

    @Override
    public Integer value5() {
        return getTechproductid();
    }

    @Override
    public Integer value6() {
        return getDishid();
    }

    @Override
    public String value7() {
        return getCategory();
    }

    @Override
    public DishRecord value1(String value) {
        setDishname(value);
        return this;
    }

    @Override
    public DishRecord value2(Double value) {
        setWeight(value);
        return this;
    }

    @Override
    public DishRecord value3(Double value) {
        setFirstcost(value);
        return this;
    }

    @Override
    public DishRecord value4(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public DishRecord value5(Integer value) {
        setTechproductid(value);
        return this;
    }

    @Override
    public DishRecord value6(Integer value) {
        setDishid(value);
        return this;
    }

    @Override
    public DishRecord value7(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public DishRecord values(String value1, Double value2, Double value3, Double value4, Integer value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DishRecord
     */
    public DishRecord() {
        super(Dish.DISH);
    }

    /**
     * Create a detached, initialised DishRecord
     */
    public DishRecord(String dishname, Double weight, Double firstcost, Double price, Integer techproductid, Integer dishid, String category) {
        super(Dish.DISH);

        setDishname(dishname);
        setWeight(weight);
        setFirstcost(firstcost);
        setPrice(price);
        setTechproductid(techproductid);
        setDishid(dishid);
        setCategory(category);
        resetChangedOnNotNull();
    }
}
