/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.DishSetItem;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DishSetItemRecord extends UpdatableRecordImpl<DishSetItemRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.dish_set_item.set_item_id</code>.
     */
    public void setSetItemId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.dish_set_item.set_item_id</code>.
     */
    public Integer getSetItemId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.dish_set_item.set_id</code>.
     */
    public void setSetId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.dish_set_item.set_id</code>.
     */
    public Integer getSetId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.dish_set_item.dish_id</code>.
     */
    public void setDishId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.dish_set_item.dish_id</code>.
     */
    public Integer getDishId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sales.dish_set_item.qty</code>.
     */
    public void setQty(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.dish_set_item.qty</code>.
     */
    public Integer getQty() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DishSetItem.DISH_SET_ITEM.SET_ITEM_ID;
    }

    @Override
    public Field<Integer> field2() {
        return DishSetItem.DISH_SET_ITEM.SET_ID;
    }

    @Override
    public Field<Integer> field3() {
        return DishSetItem.DISH_SET_ITEM.DISH_ID;
    }

    @Override
    public Field<Integer> field4() {
        return DishSetItem.DISH_SET_ITEM.QTY;
    }

    @Override
    public Integer component1() {
        return getSetItemId();
    }

    @Override
    public Integer component2() {
        return getSetId();
    }

    @Override
    public Integer component3() {
        return getDishId();
    }

    @Override
    public Integer component4() {
        return getQty();
    }

    @Override
    public Integer value1() {
        return getSetItemId();
    }

    @Override
    public Integer value2() {
        return getSetId();
    }

    @Override
    public Integer value3() {
        return getDishId();
    }

    @Override
    public Integer value4() {
        return getQty();
    }

    @Override
    public DishSetItemRecord value1(Integer value) {
        setSetItemId(value);
        return this;
    }

    @Override
    public DishSetItemRecord value2(Integer value) {
        setSetId(value);
        return this;
    }

    @Override
    public DishSetItemRecord value3(Integer value) {
        setDishId(value);
        return this;
    }

    @Override
    public DishSetItemRecord value4(Integer value) {
        setQty(value);
        return this;
    }

    @Override
    public DishSetItemRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DishSetItemRecord
     */
    public DishSetItemRecord() {
        super(DishSetItem.DISH_SET_ITEM);
    }

    /**
     * Create a detached, initialised DishSetItemRecord
     */
    public DishSetItemRecord(Integer setItemId, Integer setId, Integer dishId, Integer qty) {
        super(DishSetItem.DISH_SET_ITEM);

        setSetItemId(setItemId);
        setSetId(setId);
        setDishId(dishId);
        setQty(qty);
        resetChangedOnNotNull();
    }
}
