/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.OffsetDateTime;

import jooqdata.tables.DishCategory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DishCategoryRecord extends UpdatableRecordImpl<DishCategoryRecord> implements Record3<Integer, String, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.dish_category.category_id</code>.
     */
    public void setCategoryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.dish_category.category_id</code>.
     */
    public Integer getCategoryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.dish_category.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.dish_category.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sales.dish_category.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.dish_category.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, OffsetDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DishCategory.DISH_CATEGORY.CATEGORY_ID;
    }

    @Override
    public Field<String> field2() {
        return DishCategory.DISH_CATEGORY.NAME;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return DishCategory.DISH_CATEGORY.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getCategoryId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getCategoryId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public DishCategoryRecord value1(Integer value) {
        setCategoryId(value);
        return this;
    }

    @Override
    public DishCategoryRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public DishCategoryRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public DishCategoryRecord values(Integer value1, String value2, OffsetDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DishCategoryRecord
     */
    public DishCategoryRecord() {
        super(DishCategory.DISH_CATEGORY);
    }

    /**
     * Create a detached, initialised DishCategoryRecord
     */
    public DishCategoryRecord(Integer categoryId, String name, OffsetDateTime createdAt) {
        super(DishCategory.DISH_CATEGORY);

        setCategoryId(categoryId);
        setName(name);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
