/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.DishSet;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DishSetRecord extends UpdatableRecordImpl<DishSetRecord> implements Record5<Integer, String, Double, Double, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.dish_set.setid</code>.
     */
    public void setSetid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.dish_set.setid</code>.
     */
    public Integer getSetid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.dish_set.setname</code>.
     */
    public void setSetname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.dish_set.setname</code>.
     */
    public String getSetname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sales.dish_set.price</code>.
     */
    public void setPrice(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.dish_set.price</code>.
     */
    public Double getPrice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>sales.dish_set.first_cost</code>.
     */
    public void setFirstCost(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.dish_set.first_cost</code>.
     */
    public Double getFirstCost() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>sales.dish_set.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.dish_set.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Double, Double, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Double, Double, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DishSet.DISH_SET.SETID;
    }

    @Override
    public Field<String> field2() {
        return DishSet.DISH_SET.SETNAME;
    }

    @Override
    public Field<Double> field3() {
        return DishSet.DISH_SET.PRICE;
    }

    @Override
    public Field<Double> field4() {
        return DishSet.DISH_SET.FIRST_COST;
    }

    @Override
    public Field<String> field5() {
        return DishSet.DISH_SET.IMAGE_URL;
    }

    @Override
    public Integer component1() {
        return getSetid();
    }

    @Override
    public String component2() {
        return getSetname();
    }

    @Override
    public Double component3() {
        return getPrice();
    }

    @Override
    public Double component4() {
        return getFirstCost();
    }

    @Override
    public String component5() {
        return getImageUrl();
    }

    @Override
    public Integer value1() {
        return getSetid();
    }

    @Override
    public String value2() {
        return getSetname();
    }

    @Override
    public Double value3() {
        return getPrice();
    }

    @Override
    public Double value4() {
        return getFirstCost();
    }

    @Override
    public String value5() {
        return getImageUrl();
    }

    @Override
    public DishSetRecord value1(Integer value) {
        setSetid(value);
        return this;
    }

    @Override
    public DishSetRecord value2(String value) {
        setSetname(value);
        return this;
    }

    @Override
    public DishSetRecord value3(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public DishSetRecord value4(Double value) {
        setFirstCost(value);
        return this;
    }

    @Override
    public DishSetRecord value5(String value) {
        setImageUrl(value);
        return this;
    }

    @Override
    public DishSetRecord values(Integer value1, String value2, Double value3, Double value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DishSetRecord
     */
    public DishSetRecord() {
        super(DishSet.DISH_SET);
    }

    /**
     * Create a detached, initialised DishSetRecord
     */
    public DishSetRecord(Integer setid, String setname, Double price, Double firstCost, String imageUrl) {
        super(DishSet.DISH_SET);

        setSetid(setid);
        setSetname(setname);
        setPrice(price);
        setFirstCost(firstCost);
        setImageUrl(imageUrl);
        resetChangedOnNotNull();
    }
}
