/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.math.BigDecimal;

import jooqdata.tables.Favoriteproduct;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FavoriteproductRecord extends UpdatableRecordImpl<FavoriteproductRecord> implements Record5<Integer, Integer, String, BigDecimal, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.favoriteproduct.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.favoriteproduct.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.favoriteproduct.supplierid</code>.
     */
    public void setSupplierid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.favoriteproduct.supplierid</code>.
     */
    public Integer getSupplierid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.favoriteproduct.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.favoriteproduct.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sales.favoriteproduct.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.favoriteproduct.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>sales.favoriteproduct.data</code>.
     */
    public void setData(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.favoriteproduct.data</code>.
     */
    public String getData() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, BigDecimal, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, BigDecimal, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Favoriteproduct.FAVORITEPRODUCT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Favoriteproduct.FAVORITEPRODUCT.SUPPLIERID;
    }

    @Override
    public Field<String> field3() {
        return Favoriteproduct.FAVORITEPRODUCT.NAME;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Favoriteproduct.FAVORITEPRODUCT.PRICE;
    }

    @Override
    public Field<String> field5() {
        return Favoriteproduct.FAVORITEPRODUCT.DATA;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getSupplierid();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public BigDecimal component4() {
        return getPrice();
    }

    @Override
    public String component5() {
        return getData();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getSupplierid();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public BigDecimal value4() {
        return getPrice();
    }

    @Override
    public String value5() {
        return getData();
    }

    @Override
    public FavoriteproductRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FavoriteproductRecord value2(Integer value) {
        setSupplierid(value);
        return this;
    }

    @Override
    public FavoriteproductRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public FavoriteproductRecord value4(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public FavoriteproductRecord value5(String value) {
        setData(value);
        return this;
    }

    @Override
    public FavoriteproductRecord values(Integer value1, Integer value2, String value3, BigDecimal value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FavoriteproductRecord
     */
    public FavoriteproductRecord() {
        super(Favoriteproduct.FAVORITEPRODUCT);
    }

    /**
     * Create a detached, initialised FavoriteproductRecord
     */
    public FavoriteproductRecord(Integer id, Integer supplierid, String name, BigDecimal price, String data) {
        super(Favoriteproduct.FAVORITEPRODUCT);

        setId(id);
        setSupplierid(supplierid);
        setName(name);
        setPrice(price);
        setData(data);
        resetChangedOnNotNull();
    }
}
