/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDate;

import jooqdata.tables.Favoriteproduct;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FavoriteproductRecord extends UpdatableRecordImpl<FavoriteproductRecord> implements Record4<Integer, Integer, LocalDate, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.favoriteproduct.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.favoriteproduct.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.favoriteproduct.supplierid</code>.
     */
    public void setSupplierid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.favoriteproduct.supplierid</code>.
     */
    public Integer getSupplierid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.favoriteproduct.date</code>.
     */
    public void setDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.favoriteproduct.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>sales.favoriteproduct.productid</code>.
     */
    public void setProductid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.favoriteproduct.productid</code>.
     */
    public Integer getProductid() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, LocalDate, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, LocalDate, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Favoriteproduct.FAVORITEPRODUCT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Favoriteproduct.FAVORITEPRODUCT.SUPPLIERID;
    }

    @Override
    public Field<LocalDate> field3() {
        return Favoriteproduct.FAVORITEPRODUCT.DATE;
    }

    @Override
    public Field<Integer> field4() {
        return Favoriteproduct.FAVORITEPRODUCT.PRODUCTID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getSupplierid();
    }

    @Override
    public LocalDate component3() {
        return getDate();
    }

    @Override
    public Integer component4() {
        return getProductid();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getSupplierid();
    }

    @Override
    public LocalDate value3() {
        return getDate();
    }

    @Override
    public Integer value4() {
        return getProductid();
    }

    @Override
    public FavoriteproductRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FavoriteproductRecord value2(Integer value) {
        setSupplierid(value);
        return this;
    }

    @Override
    public FavoriteproductRecord value3(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public FavoriteproductRecord value4(Integer value) {
        setProductid(value);
        return this;
    }

    @Override
    public FavoriteproductRecord values(Integer value1, Integer value2, LocalDate value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FavoriteproductRecord
     */
    public FavoriteproductRecord() {
        super(Favoriteproduct.FAVORITEPRODUCT);
    }

    /**
     * Create a detached, initialised FavoriteproductRecord
     */
    public FavoriteproductRecord(Integer id, Integer supplierid, LocalDate date, Integer productid) {
        super(Favoriteproduct.FAVORITEPRODUCT);

        setId(id);
        setSupplierid(supplierid);
        setDate(date);
        setProductid(productid);
        resetChangedOnNotNull();
    }
}
