/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;

import jooqdata.tables.InventoryDocuments;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InventoryDocumentsRecord extends UpdatableRecordImpl<InventoryDocumentsRecord> implements Record10<Integer, String, LocalDateTime, Integer, Integer, Integer, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.inventory_documents.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.inventory_documents.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.inventory_documents.doc_type</code>.
     */
    public void setDocType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.inventory_documents.doc_type</code>.
     */
    public String getDocType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sales.inventory_documents.doc_date</code>.
     */
    public void setDocDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.inventory_documents.doc_date</code>.
     */
    public LocalDateTime getDocDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>sales.inventory_documents.supplier_id</code>.
     */
    public void setSupplierId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.inventory_documents.supplier_id</code>.
     */
    public Integer getSupplierId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sales.inventory_documents.warehouse_from_id</code>.
     */
    public void setWarehouseFromId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.inventory_documents.warehouse_from_id</code>.
     */
    public Integer getWarehouseFromId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sales.inventory_documents.warehouse_to_id</code>.
     */
    public void setWarehouseToId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>sales.inventory_documents.warehouse_to_id</code>.
     */
    public Integer getWarehouseToId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>sales.inventory_documents.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sales.inventory_documents.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sales.inventory_documents.comment</code>.
     */
    public void setComment(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>sales.inventory_documents.comment</code>.
     */
    public String getComment() {
        return (String) get(7);
    }

    /**
     * Setter for <code>sales.inventory_documents.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>sales.inventory_documents.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>sales.inventory_documents.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>sales.inventory_documents.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, LocalDateTime, Integer, Integer, Integer, String, String, String, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, LocalDateTime, Integer, Integer, Integer, String, String, String, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return InventoryDocuments.INVENTORY_DOCUMENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return InventoryDocuments.INVENTORY_DOCUMENTS.DOC_TYPE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return InventoryDocuments.INVENTORY_DOCUMENTS.DOC_DATE;
    }

    @Override
    public Field<Integer> field4() {
        return InventoryDocuments.INVENTORY_DOCUMENTS.SUPPLIER_ID;
    }

    @Override
    public Field<Integer> field5() {
        return InventoryDocuments.INVENTORY_DOCUMENTS.WAREHOUSE_FROM_ID;
    }

    @Override
    public Field<Integer> field6() {
        return InventoryDocuments.INVENTORY_DOCUMENTS.WAREHOUSE_TO_ID;
    }

    @Override
    public Field<String> field7() {
        return InventoryDocuments.INVENTORY_DOCUMENTS.STATUS;
    }

    @Override
    public Field<String> field8() {
        return InventoryDocuments.INVENTORY_DOCUMENTS.COMMENT;
    }

    @Override
    public Field<String> field9() {
        return InventoryDocuments.INVENTORY_DOCUMENTS.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return InventoryDocuments.INVENTORY_DOCUMENTS.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDocType();
    }

    @Override
    public LocalDateTime component3() {
        return getDocDate();
    }

    @Override
    public Integer component4() {
        return getSupplierId();
    }

    @Override
    public Integer component5() {
        return getWarehouseFromId();
    }

    @Override
    public Integer component6() {
        return getWarehouseToId();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public String component8() {
        return getComment();
    }

    @Override
    public String component9() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDocType();
    }

    @Override
    public LocalDateTime value3() {
        return getDocDate();
    }

    @Override
    public Integer value4() {
        return getSupplierId();
    }

    @Override
    public Integer value5() {
        return getWarehouseFromId();
    }

    @Override
    public Integer value6() {
        return getWarehouseToId();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public String value8() {
        return getComment();
    }

    @Override
    public String value9() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public InventoryDocumentsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public InventoryDocumentsRecord value2(String value) {
        setDocType(value);
        return this;
    }

    @Override
    public InventoryDocumentsRecord value3(LocalDateTime value) {
        setDocDate(value);
        return this;
    }

    @Override
    public InventoryDocumentsRecord value4(Integer value) {
        setSupplierId(value);
        return this;
    }

    @Override
    public InventoryDocumentsRecord value5(Integer value) {
        setWarehouseFromId(value);
        return this;
    }

    @Override
    public InventoryDocumentsRecord value6(Integer value) {
        setWarehouseToId(value);
        return this;
    }

    @Override
    public InventoryDocumentsRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public InventoryDocumentsRecord value8(String value) {
        setComment(value);
        return this;
    }

    @Override
    public InventoryDocumentsRecord value9(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public InventoryDocumentsRecord value10(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public InventoryDocumentsRecord values(Integer value1, String value2, LocalDateTime value3, Integer value4, Integer value5, Integer value6, String value7, String value8, String value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryDocumentsRecord
     */
    public InventoryDocumentsRecord() {
        super(InventoryDocuments.INVENTORY_DOCUMENTS);
    }

    /**
     * Create a detached, initialised InventoryDocumentsRecord
     */
    public InventoryDocumentsRecord(Integer id, String docType, LocalDateTime docDate, Integer supplierId, Integer warehouseFromId, Integer warehouseToId, String status, String comment, String createdBy, LocalDateTime createdAt) {
        super(InventoryDocuments.INVENTORY_DOCUMENTS);

        setId(id);
        setDocType(docType);
        setDocDate(docDate);
        setSupplierId(supplierId);
        setWarehouseFromId(warehouseFromId);
        setWarehouseToId(warehouseToId);
        setStatus(status);
        setComment(comment);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
