/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import jooqdata.tables.Order;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> implements Record17<Integer, LocalDate, Integer, Double, Boolean, Integer, Boolean, Double, Double, LocalDateTime, Boolean, LocalDate, LocalDate, String, String, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.order.shiftid</code>.
     */
    public void setShiftid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.order.shiftid</code>.
     */
    public Integer getShiftid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.order.Date</code>.
     */
    public void setDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.order.Date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>sales.order.clientid</code>.
     */
    public void setClientid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.order.clientid</code>.
     */
    public Integer getClientid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sales.order.amount</code>.
     */
    public void setAmount(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.order.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>sales.order.status</code>.
     */
    public void setStatus(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.order.status</code>.
     */
    public Boolean getStatus() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>sales.order.orderid</code>.
     */
    public void setOrderid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>sales.order.orderid</code>.
     */
    public Integer getOrderid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>sales.order.type</code>.
     */
    public void setType(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>sales.order.type</code>.
     */
    public Boolean getType() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>sales.order.time</code>.
     */
    public void setTime(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>sales.order.time</code>.
     */
    public Double getTime() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>sales.order.timedelay</code>.
     */
    public void setTimedelay(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>sales.order.timedelay</code>.
     */
    public Double getTimedelay() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>sales.order.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>sales.order.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>sales.order.duty</code>.
     */
    public void setDuty(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>sales.order.duty</code>.
     */
    public Boolean getDuty() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>sales.order.date_issue</code>.
     */
    public void setDateIssue(LocalDate value) {
        set(11, value);
    }

    /**
     * Getter for <code>sales.order.date_issue</code>.
     */
    public LocalDate getDateIssue() {
        return (LocalDate) get(11);
    }

    /**
     * Setter for <code>sales.order.debt_payment_date</code>.
     */
    public void setDebtPaymentDate(LocalDate value) {
        set(12, value);
    }

    /**
     * Getter for <code>sales.order.debt_payment_date</code>.
     */
    public LocalDate getDebtPaymentDate() {
        return (LocalDate) get(12);
    }

    /**
     * Setter for <code>sales.order.delivery_phone</code>.
     */
    public void setDeliveryPhone(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>sales.order.delivery_phone</code>.
     */
    public String getDeliveryPhone() {
        return (String) get(13);
    }

    /**
     * Setter for <code>sales.order.delivery_address</code>.
     */
    public void setDeliveryAddress(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>sales.order.delivery_address</code>.
     */
    public String getDeliveryAddress() {
        return (String) get(14);
    }

    /**
     * Setter for <code>sales.order.payment_type</code>.
     */
    public void setPaymentType(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>sales.order.payment_type</code>.
     */
    public String getPaymentType() {
        return (String) get(15);
    }

    /**
     * Setter for <code>sales.order.is_paid</code>.
     */
    public void setIsPaid(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>sales.order.is_paid</code>.
     */
    public Boolean getIsPaid() {
        return (Boolean) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Integer, LocalDate, Integer, Double, Boolean, Integer, Boolean, Double, Double, LocalDateTime, Boolean, LocalDate, LocalDate, String, String, String, Boolean> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Integer, LocalDate, Integer, Double, Boolean, Integer, Boolean, Double, Double, LocalDateTime, Boolean, LocalDate, LocalDate, String, String, String, Boolean> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Order.ORDER.SHIFTID;
    }

    @Override
    public Field<LocalDate> field2() {
        return Order.ORDER.DATE;
    }

    @Override
    public Field<Integer> field3() {
        return Order.ORDER.CLIENTID;
    }

    @Override
    public Field<Double> field4() {
        return Order.ORDER.AMOUNT;
    }

    @Override
    public Field<Boolean> field5() {
        return Order.ORDER.STATUS;
    }

    @Override
    public Field<Integer> field6() {
        return Order.ORDER.ORDERID;
    }

    @Override
    public Field<Boolean> field7() {
        return Order.ORDER.TYPE;
    }

    @Override
    public Field<Double> field8() {
        return Order.ORDER.TIME;
    }

    @Override
    public Field<Double> field9() {
        return Order.ORDER.TIMEDELAY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Order.ORDER.CREATED_AT;
    }

    @Override
    public Field<Boolean> field11() {
        return Order.ORDER.DUTY;
    }

    @Override
    public Field<LocalDate> field12() {
        return Order.ORDER.DATE_ISSUE;
    }

    @Override
    public Field<LocalDate> field13() {
        return Order.ORDER.DEBT_PAYMENT_DATE;
    }

    @Override
    public Field<String> field14() {
        return Order.ORDER.DELIVERY_PHONE;
    }

    @Override
    public Field<String> field15() {
        return Order.ORDER.DELIVERY_ADDRESS;
    }

    @Override
    public Field<String> field16() {
        return Order.ORDER.PAYMENT_TYPE;
    }

    @Override
    public Field<Boolean> field17() {
        return Order.ORDER.IS_PAID;
    }

    @Override
    public Integer component1() {
        return getShiftid();
    }

    @Override
    public LocalDate component2() {
        return getDate();
    }

    @Override
    public Integer component3() {
        return getClientid();
    }

    @Override
    public Double component4() {
        return getAmount();
    }

    @Override
    public Boolean component5() {
        return getStatus();
    }

    @Override
    public Integer component6() {
        return getOrderid();
    }

    @Override
    public Boolean component7() {
        return getType();
    }

    @Override
    public Double component8() {
        return getTime();
    }

    @Override
    public Double component9() {
        return getTimedelay();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public Boolean component11() {
        return getDuty();
    }

    @Override
    public LocalDate component12() {
        return getDateIssue();
    }

    @Override
    public LocalDate component13() {
        return getDebtPaymentDate();
    }

    @Override
    public String component14() {
        return getDeliveryPhone();
    }

    @Override
    public String component15() {
        return getDeliveryAddress();
    }

    @Override
    public String component16() {
        return getPaymentType();
    }

    @Override
    public Boolean component17() {
        return getIsPaid();
    }

    @Override
    public Integer value1() {
        return getShiftid();
    }

    @Override
    public LocalDate value2() {
        return getDate();
    }

    @Override
    public Integer value3() {
        return getClientid();
    }

    @Override
    public Double value4() {
        return getAmount();
    }

    @Override
    public Boolean value5() {
        return getStatus();
    }

    @Override
    public Integer value6() {
        return getOrderid();
    }

    @Override
    public Boolean value7() {
        return getType();
    }

    @Override
    public Double value8() {
        return getTime();
    }

    @Override
    public Double value9() {
        return getTimedelay();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public Boolean value11() {
        return getDuty();
    }

    @Override
    public LocalDate value12() {
        return getDateIssue();
    }

    @Override
    public LocalDate value13() {
        return getDebtPaymentDate();
    }

    @Override
    public String value14() {
        return getDeliveryPhone();
    }

    @Override
    public String value15() {
        return getDeliveryAddress();
    }

    @Override
    public String value16() {
        return getPaymentType();
    }

    @Override
    public Boolean value17() {
        return getIsPaid();
    }

    @Override
    public OrderRecord value1(Integer value) {
        setShiftid(value);
        return this;
    }

    @Override
    public OrderRecord value2(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public OrderRecord value3(Integer value) {
        setClientid(value);
        return this;
    }

    @Override
    public OrderRecord value4(Double value) {
        setAmount(value);
        return this;
    }

    @Override
    public OrderRecord value5(Boolean value) {
        setStatus(value);
        return this;
    }

    @Override
    public OrderRecord value6(Integer value) {
        setOrderid(value);
        return this;
    }

    @Override
    public OrderRecord value7(Boolean value) {
        setType(value);
        return this;
    }

    @Override
    public OrderRecord value8(Double value) {
        setTime(value);
        return this;
    }

    @Override
    public OrderRecord value9(Double value) {
        setTimedelay(value);
        return this;
    }

    @Override
    public OrderRecord value10(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public OrderRecord value11(Boolean value) {
        setDuty(value);
        return this;
    }

    @Override
    public OrderRecord value12(LocalDate value) {
        setDateIssue(value);
        return this;
    }

    @Override
    public OrderRecord value13(LocalDate value) {
        setDebtPaymentDate(value);
        return this;
    }

    @Override
    public OrderRecord value14(String value) {
        setDeliveryPhone(value);
        return this;
    }

    @Override
    public OrderRecord value15(String value) {
        setDeliveryAddress(value);
        return this;
    }

    @Override
    public OrderRecord value16(String value) {
        setPaymentType(value);
        return this;
    }

    @Override
    public OrderRecord value17(Boolean value) {
        setIsPaid(value);
        return this;
    }

    @Override
    public OrderRecord values(Integer value1, LocalDate value2, Integer value3, Double value4, Boolean value5, Integer value6, Boolean value7, Double value8, Double value9, LocalDateTime value10, Boolean value11, LocalDate value12, LocalDate value13, String value14, String value15, String value16, Boolean value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(Order.ORDER);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(Integer shiftid, LocalDate date, Integer clientid, Double amount, Boolean status, Integer orderid, Boolean type, Double time, Double timedelay, LocalDateTime createdAt, Boolean duty, LocalDate dateIssue, LocalDate debtPaymentDate, String deliveryPhone, String deliveryAddress, String paymentType, Boolean isPaid) {
        super(Order.ORDER);

        setShiftid(shiftid);
        setDate(date);
        setClientid(clientid);
        setAmount(amount);
        setStatus(status);
        setOrderid(orderid);
        setType(type);
        setTime(time);
        setTimedelay(timedelay);
        setCreatedAt(createdAt);
        setDuty(duty);
        setDateIssue(dateIssue);
        setDebtPaymentDate(debtPaymentDate);
        setDeliveryPhone(deliveryPhone);
        setDeliveryAddress(deliveryAddress);
        setPaymentType(paymentType);
        setIsPaid(isPaid);
        resetChangedOnNotNull();
    }
}
