/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDate;

import jooqdata.tables.Order;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> implements Record5<Integer, Integer, LocalDate, Integer, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.order.orderid</code>.
     */
    public void setOrderid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.order.orderid</code>.
     */
    public Integer getOrderid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.order.shiftid</code>.
     */
    public void setShiftid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.order.shiftid</code>.
     */
    public Integer getShiftid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.order.Date</code>.
     */
    public void setDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.order.Date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>sales.order.clientid</code>.
     */
    public void setClientid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.order.clientid</code>.
     */
    public Integer getClientid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sales.order.amount</code>.
     */
    public void setAmount(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.order.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, LocalDate, Integer, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, LocalDate, Integer, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Order.ORDER.ORDERID;
    }

    @Override
    public Field<Integer> field2() {
        return Order.ORDER.SHIFTID;
    }

    @Override
    public Field<LocalDate> field3() {
        return Order.ORDER.DATE;
    }

    @Override
    public Field<Integer> field4() {
        return Order.ORDER.CLIENTID;
    }

    @Override
    public Field<Double> field5() {
        return Order.ORDER.AMOUNT;
    }

    @Override
    public Integer component1() {
        return getOrderid();
    }

    @Override
    public Integer component2() {
        return getShiftid();
    }

    @Override
    public LocalDate component3() {
        return getDate();
    }

    @Override
    public Integer component4() {
        return getClientid();
    }

    @Override
    public Double component5() {
        return getAmount();
    }

    @Override
    public Integer value1() {
        return getOrderid();
    }

    @Override
    public Integer value2() {
        return getShiftid();
    }

    @Override
    public LocalDate value3() {
        return getDate();
    }

    @Override
    public Integer value4() {
        return getClientid();
    }

    @Override
    public Double value5() {
        return getAmount();
    }

    @Override
    public OrderRecord value1(Integer value) {
        setOrderid(value);
        return this;
    }

    @Override
    public OrderRecord value2(Integer value) {
        setShiftid(value);
        return this;
    }

    @Override
    public OrderRecord value3(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public OrderRecord value4(Integer value) {
        setClientid(value);
        return this;
    }

    @Override
    public OrderRecord value5(Double value) {
        setAmount(value);
        return this;
    }

    @Override
    public OrderRecord values(Integer value1, Integer value2, LocalDate value3, Integer value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(Order.ORDER);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(Integer orderid, Integer shiftid, LocalDate date, Integer clientid, Double amount) {
        super(Order.ORDER);

        setOrderid(orderid);
        setShiftid(shiftid);
        setDate(date);
        setClientid(clientid);
        setAmount(amount);
        resetChangedOnNotNull();
    }
}
