/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Orderdish;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderdishRecord extends UpdatableRecordImpl<OrderdishRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.orderdish.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.orderdish.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.orderdish.orderid</code>.
     */
    public void setOrderid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.orderdish.orderid</code>.
     */
    public Integer getOrderid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.orderdish.dishid</code>.
     */
    public void setDishid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.orderdish.dishid</code>.
     */
    public Integer getDishid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sales.orderdish.qty</code>.
     */
    public void setQty(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.orderdish.qty</code>.
     */
    public Integer getQty() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Orderdish.ORDERDISH.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Orderdish.ORDERDISH.ORDERID;
    }

    @Override
    public Field<Integer> field3() {
        return Orderdish.ORDERDISH.DISHID;
    }

    @Override
    public Field<Integer> field4() {
        return Orderdish.ORDERDISH.QTY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getOrderid();
    }

    @Override
    public Integer component3() {
        return getDishid();
    }

    @Override
    public Integer component4() {
        return getQty();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getOrderid();
    }

    @Override
    public Integer value3() {
        return getDishid();
    }

    @Override
    public Integer value4() {
        return getQty();
    }

    @Override
    public OrderdishRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrderdishRecord value2(Integer value) {
        setOrderid(value);
        return this;
    }

    @Override
    public OrderdishRecord value3(Integer value) {
        setDishid(value);
        return this;
    }

    @Override
    public OrderdishRecord value4(Integer value) {
        setQty(value);
        return this;
    }

    @Override
    public OrderdishRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderdishRecord
     */
    public OrderdishRecord() {
        super(Orderdish.ORDERDISH);
    }

    /**
     * Create a detached, initialised OrderdishRecord
     */
    public OrderdishRecord(Integer id, Integer orderid, Integer dishid, Integer qty) {
        super(Orderdish.ORDERDISH);

        setId(id);
        setOrderid(orderid);
        setDishid(dishid);
        setQty(qty);
        resetChangedOnNotNull();
    }
}
