/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.math.BigDecimal;

import jooqdata.tables.Person;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PersonRecord extends UpdatableRecordImpl<PersonRecord> implements Record3<String, BigDecimal, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.person.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.person.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sales.person.salaryperday</code>.
     */
    public void setSalaryperday(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.person.salaryperday</code>.
     */
    public BigDecimal getSalaryperday() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>sales.person.personid</code>.
     */
    public void setPersonid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.person.personid</code>.
     */
    public Integer getPersonid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, BigDecimal, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, BigDecimal, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Person.PERSON.NAME;
    }

    @Override
    public Field<BigDecimal> field2() {
        return Person.PERSON.SALARYPERDAY;
    }

    @Override
    public Field<Integer> field3() {
        return Person.PERSON.PERSONID;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public BigDecimal component2() {
        return getSalaryperday();
    }

    @Override
    public Integer component3() {
        return getPersonid();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public BigDecimal value2() {
        return getSalaryperday();
    }

    @Override
    public Integer value3() {
        return getPersonid();
    }

    @Override
    public PersonRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public PersonRecord value2(BigDecimal value) {
        setSalaryperday(value);
        return this;
    }

    @Override
    public PersonRecord value3(Integer value) {
        setPersonid(value);
        return this;
    }

    @Override
    public PersonRecord values(String value1, BigDecimal value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonRecord
     */
    public PersonRecord() {
        super(Person.PERSON);
    }

    /**
     * Create a detached, initialised PersonRecord
     */
    public PersonRecord(String name, BigDecimal salaryperday, Integer personid) {
        super(Person.PERSON);

        setName(name);
        setSalaryperday(salaryperday);
        setPersonid(personid);
        resetChangedOnNotNull();
    }
}
