/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Preparation;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PreparationRecord extends UpdatableRecordImpl<PreparationRecord> implements Record3<Integer, String, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.preparation.preparationid</code>.
     */
    public void setPreparationid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.preparation.preparationid</code>.
     */
    public Integer getPreparationid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.preparation.preparationname</code>.
     */
    public void setPreparationname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.preparation.preparationname</code>.
     */
    public String getPreparationname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sales.preparation.output_weight</code>.
     */
    public void setOutputWeight(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.preparation.output_weight</code>.
     */
    public Double getOutputWeight() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Preparation.PREPARATION.PREPARATIONID;
    }

    @Override
    public Field<String> field2() {
        return Preparation.PREPARATION.PREPARATIONNAME;
    }

    @Override
    public Field<Double> field3() {
        return Preparation.PREPARATION.OUTPUT_WEIGHT;
    }

    @Override
    public Integer component1() {
        return getPreparationid();
    }

    @Override
    public String component2() {
        return getPreparationname();
    }

    @Override
    public Double component3() {
        return getOutputWeight();
    }

    @Override
    public Integer value1() {
        return getPreparationid();
    }

    @Override
    public String value2() {
        return getPreparationname();
    }

    @Override
    public Double value3() {
        return getOutputWeight();
    }

    @Override
    public PreparationRecord value1(Integer value) {
        setPreparationid(value);
        return this;
    }

    @Override
    public PreparationRecord value2(String value) {
        setPreparationname(value);
        return this;
    }

    @Override
    public PreparationRecord value3(Double value) {
        setOutputWeight(value);
        return this;
    }

    @Override
    public PreparationRecord values(Integer value1, String value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PreparationRecord
     */
    public PreparationRecord() {
        super(Preparation.PREPARATION);
    }

    /**
     * Create a detached, initialised PreparationRecord
     */
    public PreparationRecord(Integer preparationid, String preparationname, Double outputWeight) {
        super(Preparation.PREPARATION);

        setPreparationid(preparationid);
        setPreparationname(preparationname);
        setOutputWeight(outputWeight);
        resetChangedOnNotNull();
    }
}
