/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Preparationwarehouse;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PreparationwarehouseRecord extends UpdatableRecordImpl<PreparationwarehouseRecord> implements Record4<Integer, Integer, Integer, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.preparationwarehouse.warehouseid</code>.
     */
    public void setWarehouseid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.preparationwarehouse.warehouseid</code>.
     */
    public Integer getWarehouseid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.preparationwarehouse.preparationid</code>.
     */
    public void setPreparationid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.preparationwarehouse.preparationid</code>.
     */
    public Integer getPreparationid() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>sales.preparationwarehouse.preparationwarehouseid</code>.
     */
    public void setPreparationwarehouseid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>sales.preparationwarehouse.preparationwarehouseid</code>.
     */
    public Integer getPreparationwarehouseid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sales.preparationwarehouse.quantity</code>.
     */
    public void setQuantity(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.preparationwarehouse.quantity</code>.
     */
    public Double getQuantity() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Preparationwarehouse.PREPARATIONWAREHOUSE.WAREHOUSEID;
    }

    @Override
    public Field<Integer> field2() {
        return Preparationwarehouse.PREPARATIONWAREHOUSE.PREPARATIONID;
    }

    @Override
    public Field<Integer> field3() {
        return Preparationwarehouse.PREPARATIONWAREHOUSE.PREPARATIONWAREHOUSEID;
    }

    @Override
    public Field<Double> field4() {
        return Preparationwarehouse.PREPARATIONWAREHOUSE.QUANTITY;
    }

    @Override
    public Integer component1() {
        return getWarehouseid();
    }

    @Override
    public Integer component2() {
        return getPreparationid();
    }

    @Override
    public Integer component3() {
        return getPreparationwarehouseid();
    }

    @Override
    public Double component4() {
        return getQuantity();
    }

    @Override
    public Integer value1() {
        return getWarehouseid();
    }

    @Override
    public Integer value2() {
        return getPreparationid();
    }

    @Override
    public Integer value3() {
        return getPreparationwarehouseid();
    }

    @Override
    public Double value4() {
        return getQuantity();
    }

    @Override
    public PreparationwarehouseRecord value1(Integer value) {
        setWarehouseid(value);
        return this;
    }

    @Override
    public PreparationwarehouseRecord value2(Integer value) {
        setPreparationid(value);
        return this;
    }

    @Override
    public PreparationwarehouseRecord value3(Integer value) {
        setPreparationwarehouseid(value);
        return this;
    }

    @Override
    public PreparationwarehouseRecord value4(Double value) {
        setQuantity(value);
        return this;
    }

    @Override
    public PreparationwarehouseRecord values(Integer value1, Integer value2, Integer value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PreparationwarehouseRecord
     */
    public PreparationwarehouseRecord() {
        super(Preparationwarehouse.PREPARATIONWAREHOUSE);
    }

    /**
     * Create a detached, initialised PreparationwarehouseRecord
     */
    public PreparationwarehouseRecord(Integer warehouseid, Integer preparationid, Integer preparationwarehouseid, Double quantity) {
        super(Preparationwarehouse.PREPARATIONWAREHOUSE);

        setWarehouseid(warehouseid);
        setPreparationid(preparationid);
        setPreparationwarehouseid(preparationwarehouseid);
        setQuantity(quantity);
        resetChangedOnNotNull();
    }
}
