/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Productwarehouseid;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductwarehouseidRecord extends TableRecordImpl<ProductwarehouseidRecord> implements Record3<Integer, Integer, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.productwarehouseid.warehouseid</code>.
     */
    public void setWarehouseid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.productwarehouseid.warehouseid</code>.
     */
    public Integer getWarehouseid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.productwarehouseid.productid</code>.
     */
    public void setProductid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.productwarehouseid.productid</code>.
     */
    public Integer getProductid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.productwarehouseid.net</code>.
     */
    public void setNet(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.productwarehouseid.net</code>.
     */
    public Double getNet() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Productwarehouseid.PRODUCTWAREHOUSEID.WAREHOUSEID;
    }

    @Override
    public Field<Integer> field2() {
        return Productwarehouseid.PRODUCTWAREHOUSEID.PRODUCTID;
    }

    @Override
    public Field<Double> field3() {
        return Productwarehouseid.PRODUCTWAREHOUSEID.NET;
    }

    @Override
    public Integer component1() {
        return getWarehouseid();
    }

    @Override
    public Integer component2() {
        return getProductid();
    }

    @Override
    public Double component3() {
        return getNet();
    }

    @Override
    public Integer value1() {
        return getWarehouseid();
    }

    @Override
    public Integer value2() {
        return getProductid();
    }

    @Override
    public Double value3() {
        return getNet();
    }

    @Override
    public ProductwarehouseidRecord value1(Integer value) {
        setWarehouseid(value);
        return this;
    }

    @Override
    public ProductwarehouseidRecord value2(Integer value) {
        setProductid(value);
        return this;
    }

    @Override
    public ProductwarehouseidRecord value3(Double value) {
        setNet(value);
        return this;
    }

    @Override
    public ProductwarehouseidRecord values(Integer value1, Integer value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductwarehouseidRecord
     */
    public ProductwarehouseidRecord() {
        super(Productwarehouseid.PRODUCTWAREHOUSEID);
    }

    /**
     * Create a detached, initialised ProductwarehouseidRecord
     */
    public ProductwarehouseidRecord(Integer warehouseid, Integer productid, Double net) {
        super(Productwarehouseid.PRODUCTWAREHOUSEID);

        setWarehouseid(warehouseid);
        setProductid(productid);
        setNet(net);
        resetChangedOnNotNull();
    }
}
