/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Productwarehouse;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductwarehouseRecord extends UpdatableRecordImpl<ProductwarehouseRecord> implements Record4<Integer, Integer, Integer, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.productwarehouse.warehouseid</code>.
     */
    public void setWarehouseid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.productwarehouse.warehouseid</code>.
     */
    public Integer getWarehouseid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.productwarehouse.productid</code>.
     */
    public void setProductid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.productwarehouse.productid</code>.
     */
    public Integer getProductid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.productwarehouse.productwarehouseid</code>.
     */
    public void setProductwarehouseid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.productwarehouse.productwarehouseid</code>.
     */
    public Integer getProductwarehouseid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sales.productwarehouse.quantity</code>.
     */
    public void setQuantity(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.productwarehouse.quantity</code>.
     */
    public Double getQuantity() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Productwarehouse.PRODUCTWAREHOUSE.WAREHOUSEID;
    }

    @Override
    public Field<Integer> field2() {
        return Productwarehouse.PRODUCTWAREHOUSE.PRODUCTID;
    }

    @Override
    public Field<Integer> field3() {
        return Productwarehouse.PRODUCTWAREHOUSE.PRODUCTWAREHOUSEID;
    }

    @Override
    public Field<Double> field4() {
        return Productwarehouse.PRODUCTWAREHOUSE.QUANTITY;
    }

    @Override
    public Integer component1() {
        return getWarehouseid();
    }

    @Override
    public Integer component2() {
        return getProductid();
    }

    @Override
    public Integer component3() {
        return getProductwarehouseid();
    }

    @Override
    public Double component4() {
        return getQuantity();
    }

    @Override
    public Integer value1() {
        return getWarehouseid();
    }

    @Override
    public Integer value2() {
        return getProductid();
    }

    @Override
    public Integer value3() {
        return getProductwarehouseid();
    }

    @Override
    public Double value4() {
        return getQuantity();
    }

    @Override
    public ProductwarehouseRecord value1(Integer value) {
        setWarehouseid(value);
        return this;
    }

    @Override
    public ProductwarehouseRecord value2(Integer value) {
        setProductid(value);
        return this;
    }

    @Override
    public ProductwarehouseRecord value3(Integer value) {
        setProductwarehouseid(value);
        return this;
    }

    @Override
    public ProductwarehouseRecord value4(Double value) {
        setQuantity(value);
        return this;
    }

    @Override
    public ProductwarehouseRecord values(Integer value1, Integer value2, Integer value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductwarehouseRecord
     */
    public ProductwarehouseRecord() {
        super(Productwarehouse.PRODUCTWAREHOUSE);
    }

    /**
     * Create a detached, initialised ProductwarehouseRecord
     */
    public ProductwarehouseRecord(Integer warehouseid, Integer productid, Integer productwarehouseid, Double quantity) {
        super(Productwarehouse.PRODUCTWAREHOUSE);

        setWarehouseid(warehouseid);
        setProductid(productid);
        setProductwarehouseid(productwarehouseid);
        setQuantity(quantity);
        resetChangedOnNotNull();
    }
}
