/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.math.BigDecimal;

import jooqdata.tables.Product;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record6<Integer, String, BigDecimal, Double, Boolean, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.product.supplierid</code>.
     */
    public void setSupplierid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.product.supplierid</code>.
     */
    public Integer getSupplierid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.product.productname</code>.
     */
    public void setProductname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.product.productname</code>.
     */
    public String getProductname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sales.product.productprice</code>.
     */
    public void setProductprice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.product.productprice</code>.
     */
    public BigDecimal getProductprice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>sales.product.waste</code>.
     */
    public void setWaste(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.product.waste</code>.
     */
    public Double getWaste() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>sales.product.isfavourite</code>.
     */
    public void setIsfavourite(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.product.isfavourite</code>.
     */
    public Boolean getIsfavourite() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>sales.product.productid</code>.
     */
    public void setProductid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>sales.product.productid</code>.
     */
    public Integer getProductid() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, BigDecimal, Double, Boolean, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, BigDecimal, Double, Boolean, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Product.PRODUCT.SUPPLIERID;
    }

    @Override
    public Field<String> field2() {
        return Product.PRODUCT.PRODUCTNAME;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Product.PRODUCT.PRODUCTPRICE;
    }

    @Override
    public Field<Double> field4() {
        return Product.PRODUCT.WASTE;
    }

    @Override
    public Field<Boolean> field5() {
        return Product.PRODUCT.ISFAVOURITE;
    }

    @Override
    public Field<Integer> field6() {
        return Product.PRODUCT.PRODUCTID;
    }

    @Override
    public Integer component1() {
        return getSupplierid();
    }

    @Override
    public String component2() {
        return getProductname();
    }

    @Override
    public BigDecimal component3() {
        return getProductprice();
    }

    @Override
    public Double component4() {
        return getWaste();
    }

    @Override
    public Boolean component5() {
        return getIsfavourite();
    }

    @Override
    public Integer component6() {
        return getProductid();
    }

    @Override
    public Integer value1() {
        return getSupplierid();
    }

    @Override
    public String value2() {
        return getProductname();
    }

    @Override
    public BigDecimal value3() {
        return getProductprice();
    }

    @Override
    public Double value4() {
        return getWaste();
    }

    @Override
    public Boolean value5() {
        return getIsfavourite();
    }

    @Override
    public Integer value6() {
        return getProductid();
    }

    @Override
    public ProductRecord value1(Integer value) {
        setSupplierid(value);
        return this;
    }

    @Override
    public ProductRecord value2(String value) {
        setProductname(value);
        return this;
    }

    @Override
    public ProductRecord value3(BigDecimal value) {
        setProductprice(value);
        return this;
    }

    @Override
    public ProductRecord value4(Double value) {
        setWaste(value);
        return this;
    }

    @Override
    public ProductRecord value5(Boolean value) {
        setIsfavourite(value);
        return this;
    }

    @Override
    public ProductRecord value6(Integer value) {
        setProductid(value);
        return this;
    }

    @Override
    public ProductRecord values(Integer value1, String value2, BigDecimal value3, Double value4, Boolean value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Integer supplierid, String productname, BigDecimal productprice, Double waste, Boolean isfavourite, Integer productid) {
        super(Product.PRODUCT);

        setSupplierid(supplierid);
        setProductname(productname);
        setProductprice(productprice);
        setWaste(waste);
        setIsfavourite(isfavourite);
        setProductid(productid);
        resetChangedOnNotNull();
    }
}
