/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.ProductSupplier;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductSupplierRecord extends UpdatableRecordImpl<ProductSupplierRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.product_supplier.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.product_supplier.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.product_supplier.supplier_id</code>.
     */
    public void setSupplierId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.product_supplier.supplier_id</code>.
     */
    public Integer getSupplierId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ProductSupplier.PRODUCT_SUPPLIER.PRODUCT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ProductSupplier.PRODUCT_SUPPLIER.SUPPLIER_ID;
    }

    @Override
    public Integer component1() {
        return getProductId();
    }

    @Override
    public Integer component2() {
        return getSupplierId();
    }

    @Override
    public Integer value1() {
        return getProductId();
    }

    @Override
    public Integer value2() {
        return getSupplierId();
    }

    @Override
    public ProductSupplierRecord value1(Integer value) {
        setProductId(value);
        return this;
    }

    @Override
    public ProductSupplierRecord value2(Integer value) {
        setSupplierId(value);
        return this;
    }

    @Override
    public ProductSupplierRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductSupplierRecord
     */
    public ProductSupplierRecord() {
        super(ProductSupplier.PRODUCT_SUPPLIER);
    }

    /**
     * Create a detached, initialised ProductSupplierRecord
     */
    public ProductSupplierRecord(Integer productId, Integer supplierId) {
        super(ProductSupplier.PRODUCT_SUPPLIER);

        setProductId(productId);
        setSupplierId(supplierId);
        resetChangedOnNotNull();
    }
}
