/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Shiftperson;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShiftpersonRecord extends UpdatableRecordImpl<ShiftpersonRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.shiftperson.shiftpersonid</code>.
     */
    public void setShiftpersonid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.shiftperson.shiftpersonid</code>.
     */
    public Integer getShiftpersonid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.shiftperson.shiftid</code>.
     */
    public void setShiftid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.shiftperson.shiftid</code>.
     */
    public Integer getShiftid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.shiftperson.personid</code>.
     */
    public void setPersonid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.shiftperson.personid</code>.
     */
    public Integer getPersonid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Shiftperson.SHIFTPERSON.SHIFTPERSONID;
    }

    @Override
    public Field<Integer> field2() {
        return Shiftperson.SHIFTPERSON.SHIFTID;
    }

    @Override
    public Field<Integer> field3() {
        return Shiftperson.SHIFTPERSON.PERSONID;
    }

    @Override
    public Integer component1() {
        return getShiftpersonid();
    }

    @Override
    public Integer component2() {
        return getShiftid();
    }

    @Override
    public Integer component3() {
        return getPersonid();
    }

    @Override
    public Integer value1() {
        return getShiftpersonid();
    }

    @Override
    public Integer value2() {
        return getShiftid();
    }

    @Override
    public Integer value3() {
        return getPersonid();
    }

    @Override
    public ShiftpersonRecord value1(Integer value) {
        setShiftpersonid(value);
        return this;
    }

    @Override
    public ShiftpersonRecord value2(Integer value) {
        setShiftid(value);
        return this;
    }

    @Override
    public ShiftpersonRecord value3(Integer value) {
        setPersonid(value);
        return this;
    }

    @Override
    public ShiftpersonRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShiftpersonRecord
     */
    public ShiftpersonRecord() {
        super(Shiftperson.SHIFTPERSON);
    }

    /**
     * Create a detached, initialised ShiftpersonRecord
     */
    public ShiftpersonRecord(Integer shiftpersonid, Integer shiftid, Integer personid) {
        super(Shiftperson.SHIFTPERSON);

        setShiftpersonid(shiftpersonid);
        setShiftid(shiftid);
        setPersonid(personid);
        resetChangedOnNotNull();
    }
}
