/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.math.BigDecimal;
import java.time.LocalTime;

import jooqdata.tables.Shift;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShiftRecord extends UpdatableRecordImpl<ShiftRecord> implements Record6<Integer, String, LocalTime, LocalTime, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.shift.shiftid</code>.
     *
     * @return
     */
    public int setShiftid(Integer value) {
        set(0, value);
        return 0;
    }

    /**
     * Getter for <code>sales.shift.shiftid</code>.
     */
    public Integer getShiftid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.shift.data</code>.
     */
    public void setData(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.shift.data</code>.
     */
    public String getData() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sales.shift.starttime</code>.
     */
    public void setStarttime(LocalTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.shift.starttime</code>.
     */
    public LocalTime getStarttime() {
        return (LocalTime) get(2);
    }

    /**
     * Setter for <code>sales.shift.endtime</code>.
     */
    public void setEndtime(LocalTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.shift.endtime</code>.
     */
    public LocalTime getEndtime() {
        return (LocalTime) get(3);
    }

    /**
     * Setter for <code>sales.shift.profit</code>.
     */
    public void setProfit(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.shift.profit</code>.
     */
    public BigDecimal getProfit() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>sales.shift.expenses</code>.
     */
    public void setExpenses(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>sales.shift.expenses</code>.
     */
    public BigDecimal getExpenses() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, LocalTime, LocalTime, BigDecimal, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, LocalTime, LocalTime, BigDecimal, BigDecimal> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Shift.SHIFT.SHIFTID;
    }

    @Override
    public Field<String> field2() {
        return Shift.SHIFT.DATA;
    }

    @Override
    public Field<LocalTime> field3() {
        return Shift.SHIFT.STARTTIME;
    }

    @Override
    public Field<LocalTime> field4() {
        return Shift.SHIFT.ENDTIME;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Shift.SHIFT.PROFIT;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Shift.SHIFT.EXPENSES;
    }

    @Override
    public Integer component1() {
        return getShiftid();
    }

    @Override
    public String component2() {
        return getData();
    }

    @Override
    public LocalTime component3() {
        return getStarttime();
    }

    @Override
    public LocalTime component4() {
        return getEndtime();
    }

    @Override
    public BigDecimal component5() {
        return getProfit();
    }

    @Override
    public BigDecimal component6() {
        return getExpenses();
    }

    @Override
    public Integer value1() {
        return getShiftid();
    }

    @Override
    public String value2() {
        return getData();
    }

    @Override
    public LocalTime value3() {
        return getStarttime();
    }

    @Override
    public LocalTime value4() {
        return getEndtime();
    }

    @Override
    public BigDecimal value5() {
        return getProfit();
    }

    @Override
    public BigDecimal value6() {
        return getExpenses();
    }

    @Override
    public ShiftRecord value1(Integer value) {
        setShiftid(value);
        return this;
    }

    @Override
    public ShiftRecord value2(String value) {
        setData(value);
        return this;
    }

    @Override
    public ShiftRecord value3(LocalTime value) {
        setStarttime(value);
        return this;
    }

    @Override
    public ShiftRecord value4(LocalTime value) {
        setEndtime(value);
        return this;
    }

    @Override
    public ShiftRecord value5(BigDecimal value) {
        setProfit(value);
        return this;
    }

    @Override
    public ShiftRecord value6(BigDecimal value) {
        setExpenses(value);
        return this;
    }

    @Override
    public ShiftRecord values(Integer value1, String value2, LocalTime value3, LocalTime value4, BigDecimal value5, BigDecimal value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShiftRecord
     */
    public ShiftRecord() {
        super(Shift.SHIFT);
    }

    /**
     * Create a detached, initialised ShiftRecord
     */
    public ShiftRecord(Integer shiftid, String data, LocalTime starttime, LocalTime endtime, BigDecimal profit, BigDecimal expenses) {
        super(Shift.SHIFT);

        setShiftid(shiftid);
        setData(data);
        setStarttime(starttime);
        setEndtime(endtime);
        setProfit(profit);
        setExpenses(expenses);
        resetChangedOnNotNull();
    }
}
