/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import jooqdata.tables.StockMovements;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StockMovementsRecord extends UpdatableRecordImpl<StockMovementsRecord> implements Record10<Integer, LocalDateTime, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.stock_movements.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.stock_movements.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.stock_movements.movement_date</code>.
     */
    public void setMovementDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.stock_movements.movement_date</code>.
     */
    public LocalDateTime getMovementDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>sales.stock_movements.document_id</code>.
     */
    public void setDocumentId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.stock_movements.document_id</code>.
     */
    public Integer getDocumentId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sales.stock_movements.warehouse_id</code>.
     */
    public void setWarehouseId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.stock_movements.warehouse_id</code>.
     */
    public Integer getWarehouseId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sales.stock_movements.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.stock_movements.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sales.stock_movements.qty_in</code>.
     */
    public void setQtyIn(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>sales.stock_movements.qty_in</code>.
     */
    public BigDecimal getQtyIn() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>sales.stock_movements.qty_out</code>.
     */
    public void setQtyOut(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>sales.stock_movements.qty_out</code>.
     */
    public BigDecimal getQtyOut() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>sales.stock_movements.unit_cost</code>.
     */
    public void setUnitCost(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>sales.stock_movements.unit_cost</code>.
     */
    public BigDecimal getUnitCost() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>sales.stock_movements.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>sales.stock_movements.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>sales.stock_movements.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>sales.stock_movements.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, LocalDateTime, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, LocalDateTime, Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return StockMovements.STOCK_MOVEMENTS.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return StockMovements.STOCK_MOVEMENTS.MOVEMENT_DATE;
    }

    @Override
    public Field<Integer> field3() {
        return StockMovements.STOCK_MOVEMENTS.DOCUMENT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return StockMovements.STOCK_MOVEMENTS.WAREHOUSE_ID;
    }

    @Override
    public Field<Integer> field5() {
        return StockMovements.STOCK_MOVEMENTS.PRODUCT_ID;
    }

    @Override
    public Field<BigDecimal> field6() {
        return StockMovements.STOCK_MOVEMENTS.QTY_IN;
    }

    @Override
    public Field<BigDecimal> field7() {
        return StockMovements.STOCK_MOVEMENTS.QTY_OUT;
    }

    @Override
    public Field<BigDecimal> field8() {
        return StockMovements.STOCK_MOVEMENTS.UNIT_COST;
    }

    @Override
    public Field<BigDecimal> field9() {
        return StockMovements.STOCK_MOVEMENTS.AMOUNT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return StockMovements.STOCK_MOVEMENTS.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getMovementDate();
    }

    @Override
    public Integer component3() {
        return getDocumentId();
    }

    @Override
    public Integer component4() {
        return getWarehouseId();
    }

    @Override
    public Integer component5() {
        return getProductId();
    }

    @Override
    public BigDecimal component6() {
        return getQtyIn();
    }

    @Override
    public BigDecimal component7() {
        return getQtyOut();
    }

    @Override
    public BigDecimal component8() {
        return getUnitCost();
    }

    @Override
    public BigDecimal component9() {
        return getAmount();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getMovementDate();
    }

    @Override
    public Integer value3() {
        return getDocumentId();
    }

    @Override
    public Integer value4() {
        return getWarehouseId();
    }

    @Override
    public Integer value5() {
        return getProductId();
    }

    @Override
    public BigDecimal value6() {
        return getQtyIn();
    }

    @Override
    public BigDecimal value7() {
        return getQtyOut();
    }

    @Override
    public BigDecimal value8() {
        return getUnitCost();
    }

    @Override
    public BigDecimal value9() {
        return getAmount();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public StockMovementsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public StockMovementsRecord value2(LocalDateTime value) {
        setMovementDate(value);
        return this;
    }

    @Override
    public StockMovementsRecord value3(Integer value) {
        setDocumentId(value);
        return this;
    }

    @Override
    public StockMovementsRecord value4(Integer value) {
        setWarehouseId(value);
        return this;
    }

    @Override
    public StockMovementsRecord value5(Integer value) {
        setProductId(value);
        return this;
    }

    @Override
    public StockMovementsRecord value6(BigDecimal value) {
        setQtyIn(value);
        return this;
    }

    @Override
    public StockMovementsRecord value7(BigDecimal value) {
        setQtyOut(value);
        return this;
    }

    @Override
    public StockMovementsRecord value8(BigDecimal value) {
        setUnitCost(value);
        return this;
    }

    @Override
    public StockMovementsRecord value9(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public StockMovementsRecord value10(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public StockMovementsRecord values(Integer value1, LocalDateTime value2, Integer value3, Integer value4, Integer value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, BigDecimal value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StockMovementsRecord
     */
    public StockMovementsRecord() {
        super(StockMovements.STOCK_MOVEMENTS);
    }

    /**
     * Create a detached, initialised StockMovementsRecord
     */
    public StockMovementsRecord(Integer id, LocalDateTime movementDate, Integer documentId, Integer warehouseId, Integer productId, BigDecimal qtyIn, BigDecimal qtyOut, BigDecimal unitCost, BigDecimal amount, LocalDateTime createdAt) {
        super(StockMovements.STOCK_MOVEMENTS);

        setId(id);
        setMovementDate(movementDate);
        setDocumentId(documentId);
        setWarehouseId(warehouseId);
        setProductId(productId);
        setQtyIn(qtyIn);
        setQtyOut(qtyOut);
        setUnitCost(unitCost);
        setAmount(amount);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
