/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import jooqdata.tables.SupplierPriceHistory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SupplierPriceHistoryRecord extends UpdatableRecordImpl<SupplierPriceHistoryRecord> implements Record9<Integer, Integer, Integer, BigDecimal, LocalDateTime, LocalDateTime, String, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.supplier_price_history.supplier_id</code>.
     */
    public void setSupplierId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.supplier_price_history.supplier_id</code>.
     */
    public Integer getSupplierId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.supplier_price_history.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.supplier_price_history.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.supplier_price_history.id</code>.
     */
    public void setId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.supplier_price_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sales.supplier_price_history.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.supplier_price_history.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>sales.supplier_price_history.valid_from</code>.
     */
    public void setValidFrom(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.supplier_price_history.valid_from</code>.
     */
    public LocalDateTime getValidFrom() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>sales.supplier_price_history.valid_to</code>.
     */
    public void setValidTo(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>sales.supplier_price_history.valid_to</code>.
     */
    public LocalDateTime getValidTo() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>sales.supplier_price_history.source_doc_type</code>.
     */
    public void setSourceDocType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sales.supplier_price_history.source_doc_type</code>.
     */
    public String getSourceDocType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sales.supplier_price_history.source_doc_id</code>.
     */
    public void setSourceDocId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>sales.supplier_price_history.source_doc_id</code>.
     */
    public Integer getSourceDocId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>sales.supplier_price_history.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>sales.supplier_price_history.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, Integer, BigDecimal, LocalDateTime, LocalDateTime, String, Integer, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, Integer, BigDecimal, LocalDateTime, LocalDateTime, String, Integer, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SupplierPriceHistory.SUPPLIER_PRICE_HISTORY.SUPPLIER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return SupplierPriceHistory.SUPPLIER_PRICE_HISTORY.PRODUCT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return SupplierPriceHistory.SUPPLIER_PRICE_HISTORY.ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return SupplierPriceHistory.SUPPLIER_PRICE_HISTORY.PRICE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return SupplierPriceHistory.SUPPLIER_PRICE_HISTORY.VALID_FROM;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SupplierPriceHistory.SUPPLIER_PRICE_HISTORY.VALID_TO;
    }

    @Override
    public Field<String> field7() {
        return SupplierPriceHistory.SUPPLIER_PRICE_HISTORY.SOURCE_DOC_TYPE;
    }

    @Override
    public Field<Integer> field8() {
        return SupplierPriceHistory.SUPPLIER_PRICE_HISTORY.SOURCE_DOC_ID;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return SupplierPriceHistory.SUPPLIER_PRICE_HISTORY.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getSupplierId();
    }

    @Override
    public Integer component2() {
        return getProductId();
    }

    @Override
    public Integer component3() {
        return getId();
    }

    @Override
    public BigDecimal component4() {
        return getPrice();
    }

    @Override
    public LocalDateTime component5() {
        return getValidFrom();
    }

    @Override
    public LocalDateTime component6() {
        return getValidTo();
    }

    @Override
    public String component7() {
        return getSourceDocType();
    }

    @Override
    public Integer component8() {
        return getSourceDocId();
    }

    @Override
    public LocalDateTime component9() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getSupplierId();
    }

    @Override
    public Integer value2() {
        return getProductId();
    }

    @Override
    public Integer value3() {
        return getId();
    }

    @Override
    public BigDecimal value4() {
        return getPrice();
    }

    @Override
    public LocalDateTime value5() {
        return getValidFrom();
    }

    @Override
    public LocalDateTime value6() {
        return getValidTo();
    }

    @Override
    public String value7() {
        return getSourceDocType();
    }

    @Override
    public Integer value8() {
        return getSourceDocId();
    }

    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    @Override
    public SupplierPriceHistoryRecord value1(Integer value) {
        setSupplierId(value);
        return this;
    }

    @Override
    public SupplierPriceHistoryRecord value2(Integer value) {
        setProductId(value);
        return this;
    }

    @Override
    public SupplierPriceHistoryRecord value3(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SupplierPriceHistoryRecord value4(BigDecimal value) {
        setPrice(value);
        return this;
    }

    @Override
    public SupplierPriceHistoryRecord value5(LocalDateTime value) {
        setValidFrom(value);
        return this;
    }

    @Override
    public SupplierPriceHistoryRecord value6(LocalDateTime value) {
        setValidTo(value);
        return this;
    }

    @Override
    public SupplierPriceHistoryRecord value7(String value) {
        setSourceDocType(value);
        return this;
    }

    @Override
    public SupplierPriceHistoryRecord value8(Integer value) {
        setSourceDocId(value);
        return this;
    }

    @Override
    public SupplierPriceHistoryRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public SupplierPriceHistoryRecord values(Integer value1, Integer value2, Integer value3, BigDecimal value4, LocalDateTime value5, LocalDateTime value6, String value7, Integer value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplierPriceHistoryRecord
     */
    public SupplierPriceHistoryRecord() {
        super(SupplierPriceHistory.SUPPLIER_PRICE_HISTORY);
    }

    /**
     * Create a detached, initialised SupplierPriceHistoryRecord
     */
    public SupplierPriceHistoryRecord(Integer supplierId, Integer productId, Integer id, BigDecimal price, LocalDateTime validFrom, LocalDateTime validTo, String sourceDocType, Integer sourceDocId, LocalDateTime createdAt) {
        super(SupplierPriceHistory.SUPPLIER_PRICE_HISTORY);

        setSupplierId(supplierId);
        setProductId(productId);
        setId(id);
        setPrice(price);
        setValidFrom(validFrom);
        setValidTo(validTo);
        setSourceDocType(sourceDocType);
        setSourceDocId(sourceDocId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
