/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.time.LocalDateTime;

import jooqdata.tables.TaxOutbox;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TaxOutboxRecord extends UpdatableRecordImpl<TaxOutboxRecord> implements Record14<Long, String, Integer, String, String, JSONB, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.tax_outbox.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>sales.tax_outbox.aggregate_type</code>.
     */
    public void setAggregateType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.aggregate_type</code>.
     */
    public String getAggregateType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sales.tax_outbox.aggregate_id</code>.
     */
    public void setAggregateId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.aggregate_id</code>.
     */
    public Integer getAggregateId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sales.tax_outbox.event_type</code>.
     */
    public void setEventType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.event_type</code>.
     */
    public String getEventType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sales.tax_outbox.event_key</code>.
     */
    public void setEventKey(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.event_key</code>.
     */
    public String getEventKey() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sales.tax_outbox.payload_json</code>.
     */
    public void setPayloadJson(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.payload_json</code>.
     */
    public JSONB getPayloadJson() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>sales.tax_outbox.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>sales.tax_outbox.available_at</code>.
     */
    public void setAvailableAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.available_at</code>.
     */
    public LocalDateTime getAvailableAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>sales.tax_outbox.locked_at</code>.
     */
    public void setLockedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.locked_at</code>.
     */
    public LocalDateTime getLockedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>sales.tax_outbox.processed_at</code>.
     */
    public void setProcessedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.processed_at</code>.
     */
    public LocalDateTime getProcessedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>sales.tax_outbox.attempt_count</code>.
     */
    public void setAttemptCount(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.attempt_count</code>.
     */
    public Integer getAttemptCount() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>sales.tax_outbox.last_error</code>.
     */
    public void setLastError(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.last_error</code>.
     */
    public String getLastError() {
        return (String) get(11);
    }

    /**
     * Setter for <code>sales.tax_outbox.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>sales.tax_outbox.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>sales.tax_outbox.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, Integer, String, String, JSONB, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, String, Integer, String, String, JSONB, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TaxOutbox.TAX_OUTBOX.ID;
    }

    @Override
    public Field<String> field2() {
        return TaxOutbox.TAX_OUTBOX.AGGREGATE_TYPE;
    }

    @Override
    public Field<Integer> field3() {
        return TaxOutbox.TAX_OUTBOX.AGGREGATE_ID;
    }

    @Override
    public Field<String> field4() {
        return TaxOutbox.TAX_OUTBOX.EVENT_TYPE;
    }

    @Override
    public Field<String> field5() {
        return TaxOutbox.TAX_OUTBOX.EVENT_KEY;
    }

    @Override
    public Field<JSONB> field6() {
        return TaxOutbox.TAX_OUTBOX.PAYLOAD_JSON;
    }

    @Override
    public Field<String> field7() {
        return TaxOutbox.TAX_OUTBOX.STATUS;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return TaxOutbox.TAX_OUTBOX.AVAILABLE_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return TaxOutbox.TAX_OUTBOX.LOCKED_AT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return TaxOutbox.TAX_OUTBOX.PROCESSED_AT;
    }

    @Override
    public Field<Integer> field11() {
        return TaxOutbox.TAX_OUTBOX.ATTEMPT_COUNT;
    }

    @Override
    public Field<String> field12() {
        return TaxOutbox.TAX_OUTBOX.LAST_ERROR;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return TaxOutbox.TAX_OUTBOX.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return TaxOutbox.TAX_OUTBOX.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAggregateType();
    }

    @Override
    public Integer component3() {
        return getAggregateId();
    }

    @Override
    public String component4() {
        return getEventType();
    }

    @Override
    public String component5() {
        return getEventKey();
    }

    @Override
    public JSONB component6() {
        return getPayloadJson();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public LocalDateTime component8() {
        return getAvailableAt();
    }

    @Override
    public LocalDateTime component9() {
        return getLockedAt();
    }

    @Override
    public LocalDateTime component10() {
        return getProcessedAt();
    }

    @Override
    public Integer component11() {
        return getAttemptCount();
    }

    @Override
    public String component12() {
        return getLastError();
    }

    @Override
    public LocalDateTime component13() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component14() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAggregateType();
    }

    @Override
    public Integer value3() {
        return getAggregateId();
    }

    @Override
    public String value4() {
        return getEventType();
    }

    @Override
    public String value5() {
        return getEventKey();
    }

    @Override
    public JSONB value6() {
        return getPayloadJson();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public LocalDateTime value8() {
        return getAvailableAt();
    }

    @Override
    public LocalDateTime value9() {
        return getLockedAt();
    }

    @Override
    public LocalDateTime value10() {
        return getProcessedAt();
    }

    @Override
    public Integer value11() {
        return getAttemptCount();
    }

    @Override
    public String value12() {
        return getLastError();
    }

    @Override
    public LocalDateTime value13() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value14() {
        return getUpdatedAt();
    }

    @Override
    public TaxOutboxRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value2(String value) {
        setAggregateType(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value3(Integer value) {
        setAggregateId(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value4(String value) {
        setEventType(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value5(String value) {
        setEventKey(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value6(JSONB value) {
        setPayloadJson(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value8(LocalDateTime value) {
        setAvailableAt(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value9(LocalDateTime value) {
        setLockedAt(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value10(LocalDateTime value) {
        setProcessedAt(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value11(Integer value) {
        setAttemptCount(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value12(String value) {
        setLastError(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value13(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TaxOutboxRecord value14(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TaxOutboxRecord values(Long value1, String value2, Integer value3, String value4, String value5, JSONB value6, String value7, LocalDateTime value8, LocalDateTime value9, LocalDateTime value10, Integer value11, String value12, LocalDateTime value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TaxOutboxRecord
     */
    public TaxOutboxRecord() {
        super(TaxOutbox.TAX_OUTBOX);
    }

    /**
     * Create a detached, initialised TaxOutboxRecord
     */
    public TaxOutboxRecord(Long id, String aggregateType, Integer aggregateId, String eventType, String eventKey, JSONB payloadJson, String status, LocalDateTime availableAt, LocalDateTime lockedAt, LocalDateTime processedAt, Integer attemptCount, String lastError, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(TaxOutbox.TAX_OUTBOX);

        setId(id);
        setAggregateType(aggregateType);
        setAggregateId(aggregateId);
        setEventType(eventType);
        setEventKey(eventKey);
        setPayloadJson(payloadJson);
        setStatus(status);
        setAvailableAt(availableAt);
        setLockedAt(lockedAt);
        setProcessedAt(processedAt);
        setAttemptCount(attemptCount);
        setLastError(lastError);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
