/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Techproduct;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TechproductRecord extends UpdatableRecordImpl<TechproductRecord> implements Record7<Integer, Integer, Double, Double, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.techproduct.DishId</code>.
     */
    public void setDishid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.techproduct.DishId</code>.
     */
    public Integer getDishid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sales.techproduct.productid</code>.
     */
    public void setProductid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.techproduct.productid</code>.
     */
    public Integer getProductid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.techproduct.waste</code>.
     */
    public void setWaste(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.techproduct.waste</code>.
     */
    public Double getWaste() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>sales.techproduct.weight</code>.
     */
    public void setWeight(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>sales.techproduct.weight</code>.
     */
    public Double getWeight() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>sales.techproduct.techproductid</code>.
     */
    public void setTechproductid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>sales.techproduct.techproductid</code>.
     */
    public Integer getTechproductid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sales.techproduct.preparation_id</code>.
     */
    public void setPreparationId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>sales.techproduct.preparation_id</code>.
     */
    public Integer getPreparationId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>sales.techproduct.ingredient_preparation_id</code>.
     */
    public void setIngredientPreparationId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>sales.techproduct.ingredient_preparation_id</code>.
     */
    public Integer getIngredientPreparationId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Double, Double, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Double, Double, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Techproduct.TECHPRODUCT.DISHID;
    }

    @Override
    public Field<Integer> field2() {
        return Techproduct.TECHPRODUCT.PRODUCTID;
    }

    @Override
    public Field<Double> field3() {
        return Techproduct.TECHPRODUCT.WASTE;
    }

    @Override
    public Field<Double> field4() {
        return Techproduct.TECHPRODUCT.WEIGHT;
    }

    @Override
    public Field<Integer> field5() {
        return Techproduct.TECHPRODUCT.TECHPRODUCTID;
    }

    @Override
    public Field<Integer> field6() {
        return Techproduct.TECHPRODUCT.PREPARATION_ID;
    }

    @Override
    public Field<Integer> field7() {
        return Techproduct.TECHPRODUCT.INGREDIENT_PREPARATION_ID;
    }

    @Override
    public Integer component1() {
        return getDishid();
    }

    @Override
    public Integer component2() {
        return getProductid();
    }

    @Override
    public Double component3() {
        return getWaste();
    }

    @Override
    public Double component4() {
        return getWeight();
    }

    @Override
    public Integer component5() {
        return getTechproductid();
    }

    @Override
    public Integer component6() {
        return getPreparationId();
    }

    @Override
    public Integer component7() {
        return getIngredientPreparationId();
    }

    @Override
    public Integer value1() {
        return getDishid();
    }

    @Override
    public Integer value2() {
        return getProductid();
    }

    @Override
    public Double value3() {
        return getWaste();
    }

    @Override
    public Double value4() {
        return getWeight();
    }

    @Override
    public Integer value5() {
        return getTechproductid();
    }

    @Override
    public Integer value6() {
        return getPreparationId();
    }

    @Override
    public Integer value7() {
        return getIngredientPreparationId();
    }

    @Override
    public TechproductRecord value1(Integer value) {
        setDishid(value);
        return this;
    }

    @Override
    public TechproductRecord value2(Integer value) {
        setProductid(value);
        return this;
    }

    @Override
    public TechproductRecord value3(Double value) {
        setWaste(value);
        return this;
    }

    @Override
    public TechproductRecord value4(Double value) {
        setWeight(value);
        return this;
    }

    @Override
    public TechproductRecord value5(Integer value) {
        setTechproductid(value);
        return this;
    }

    @Override
    public TechproductRecord value6(Integer value) {
        setPreparationId(value);
        return this;
    }

    @Override
    public TechproductRecord value7(Integer value) {
        setIngredientPreparationId(value);
        return this;
    }

    @Override
    public TechproductRecord values(Integer value1, Integer value2, Double value3, Double value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TechproductRecord
     */
    public TechproductRecord() {
        super(Techproduct.TECHPRODUCT);
    }

    /**
     * Create a detached, initialised TechproductRecord
     */
    public TechproductRecord(Integer dishid, Integer productid, Double waste, Double weight, Integer techproductid, Integer preparationId, Integer ingredientPreparationId) {
        super(Techproduct.TECHPRODUCT);

        setDishid(dishid);
        setProductid(productid);
        setWaste(waste);
        setWeight(weight);
        setTechproductid(techproductid);
        setPreparationId(preparationId);
        setIngredientPreparationId(ingredientPreparationId);
        resetChangedOnNotNull();
    }
}
