/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import java.math.BigDecimal;

import jooqdata.tables.Warehouse;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WarehouseRecord extends UpdatableRecordImpl<WarehouseRecord> implements Record2<BigDecimal, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.warehouse.warehouseid</code>.
     */
    public void setWarehouseid(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.warehouse.warehouseid</code>.
     */
    public BigDecimal getWarehouseid() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>sales.warehouse.warehousename</code>.
     */
    public void setWarehousename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.warehouse.warehousename</code>.
     */
    public String getWarehousename() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<BigDecimal> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<BigDecimal, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<BigDecimal, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<BigDecimal> field1() {
        return Warehouse.WAREHOUSE.WAREHOUSEID;
    }

    @Override
    public Field<String> field2() {
        return Warehouse.WAREHOUSE.WAREHOUSENAME;
    }

    @Override
    public BigDecimal component1() {
        return getWarehouseid();
    }

    @Override
    public String component2() {
        return getWarehousename();
    }

    @Override
    public BigDecimal value1() {
        return getWarehouseid();
    }

    @Override
    public String value2() {
        return getWarehousename();
    }

    @Override
    public WarehouseRecord value1(BigDecimal value) {
        setWarehouseid(value);
        return this;
    }

    @Override
    public WarehouseRecord value2(String value) {
        setWarehousename(value);
        return this;
    }

    @Override
    public WarehouseRecord values(BigDecimal value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WarehouseRecord
     */
    public WarehouseRecord() {
        super(Warehouse.WAREHOUSE);
    }

    /**
     * Create a detached, initialised WarehouseRecord
     */
    public WarehouseRecord(BigDecimal warehouseid, String warehousename) {
        super(Warehouse.WAREHOUSE);

        setWarehouseid(warehouseid);
        setWarehousename(warehousename);
        resetChangedOnNotNull();
    }
}
