/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables.records;


import jooqdata.tables.Warehouse;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WarehouseRecord extends UpdatableRecordImpl<WarehouseRecord> implements Record3<String, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sales.warehouse.warehousename</code>.
     */
    public void setWarehousename(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>sales.warehouse.warehousename</code>.
     */
    public String getWarehousename() {
        return (String) get(0);
    }

    /**
     * Setter for <code>sales.warehouse.warehouseid</code>.
     */
    public void setWarehouseid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sales.warehouse.warehouseid</code>.
     */
    public Integer getWarehouseid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sales.warehouse.is_main</code>.
     */
    public void setIsMain(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>sales.warehouse.is_main</code>.
     */
    public Boolean getIsMain() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, Integer, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, Integer, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Warehouse.WAREHOUSE.WAREHOUSENAME;
    }

    @Override
    public Field<Integer> field2() {
        return Warehouse.WAREHOUSE.WAREHOUSEID;
    }

    @Override
    public Field<Boolean> field3() {
        return Warehouse.WAREHOUSE.IS_MAIN;
    }

    @Override
    public String component1() {
        return getWarehousename();
    }

    @Override
    public Integer component2() {
        return getWarehouseid();
    }

    @Override
    public Boolean component3() {
        return getIsMain();
    }

    @Override
    public String value1() {
        return getWarehousename();
    }

    @Override
    public Integer value2() {
        return getWarehouseid();
    }

    @Override
    public Boolean value3() {
        return getIsMain();
    }

    @Override
    public WarehouseRecord value1(String value) {
        setWarehousename(value);
        return this;
    }

    @Override
    public WarehouseRecord value2(Integer value) {
        setWarehouseid(value);
        return this;
    }

    @Override
    public WarehouseRecord value3(Boolean value) {
        setIsMain(value);
        return this;
    }

    @Override
    public WarehouseRecord values(String value1, Integer value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WarehouseRecord
     */
    public WarehouseRecord() {
        super(Warehouse.WAREHOUSE);
    }

    /**
     * Create a detached, initialised WarehouseRecord
     */
    public WarehouseRecord(String warehousename, Integer warehouseid, Boolean isMain) {
        super(Warehouse.WAREHOUSE);

        setWarehousename(warehousename);
        setWarehouseid(warehouseid);
        setIsMain(isMain);
        resetChangedOnNotNull();
    }
}
