/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Client.ClientPath;
import jooqdata.tables.records.ClientdishRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Clientdish extends TableImpl<ClientdishRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.clientdish</code>
     */
    public static final Clientdish CLIENTDISH = new Clientdish();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientdishRecord> getRecordType() {
        return ClientdishRecord.class;
    }

    /**
     * The column <code>sales.clientdish.dishid</code>.
     */
    public final TableField<ClientdishRecord, Integer> DISHID = createField(DSL.name("dishid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.clientdish.clientid</code>.
     */
    public final TableField<ClientdishRecord, Integer> CLIENTID = createField(DSL.name("clientid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.clientdish.dishname</code>.
     */
    public final TableField<ClientdishRecord, String> DISHNAME = createField(DSL.name("dishname"), SQLDataType.VARCHAR.nullable(false), this, "");

    private Clientdish(Name alias, Table<ClientdishRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Clientdish(Name alias, Table<ClientdishRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.clientdish</code> table reference
     */
    public Clientdish(String alias) {
        this(DSL.name(alias), CLIENTDISH);
    }

    /**
     * Create an aliased <code>sales.clientdish</code> table reference
     */
    public Clientdish(Name alias) {
        this(alias, CLIENTDISH);
    }

    /**
     * Create a <code>sales.clientdish</code> table reference
     */
    public Clientdish() {
        this(DSL.name("clientdish"), null);
    }

    public <O extends Record> Clientdish(Table<O> path, ForeignKey<O, ClientdishRecord> childPath, InverseForeignKey<O, ClientdishRecord> parentPath) {
        super(path, childPath, parentPath, CLIENTDISH);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClientdishPath extends Clientdish implements Path<ClientdishRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClientdishPath(Table<O> path, ForeignKey<O, ClientdishRecord> childPath, InverseForeignKey<O, ClientdishRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClientdishPath(Name alias, Table<ClientdishRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClientdishPath as(String alias) {
            return new ClientdishPath(DSL.name(alias), this);
        }

        @Override
        public ClientdishPath as(Name alias) {
            return new ClientdishPath(alias, this);
        }

        @Override
        public ClientdishPath as(Table<?> alias) {
            return new ClientdishPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public UniqueKey<ClientdishRecord> getPrimaryKey() {
        return Keys.CLIENTDISH_PK;
    }

    @Override
    public List<ForeignKey<ClientdishRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLIENTDISH__CLIENTDISH_CLIENT_FK);
    }

    private transient ClientPath _client;

    /**
     * Get the implicit join path to the <code>sales.client</code> table.
     */
    public ClientPath client() {
        if (_client == null)
            _client = new ClientPath(this, Keys.CLIENTDISH__CLIENTDISH_CLIENT_FK, null);

        return _client;
    }

    @Override
    public Clientdish as(String alias) {
        return new Clientdish(DSL.name(alias), this);
    }

    @Override
    public Clientdish as(Name alias) {
        return new Clientdish(alias, this);
    }

    @Override
    public Clientdish as(Table<?> alias) {
        return new Clientdish(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Clientdish rename(String name) {
        return new Clientdish(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Clientdish rename(Name name) {
        return new Clientdish(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Clientdish rename(Table<?> name) {
        return new Clientdish(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientdish where(Condition condition) {
        return new Clientdish(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientdish where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientdish where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientdish where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clientdish where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clientdish where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clientdish where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clientdish where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientdish whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientdish whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
