/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Client.ClientPath;
import jooqdata.tables.records.ClientdutyRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Clientduty extends TableImpl<ClientdutyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.clientduty</code>
     */
    public static final Clientduty CLIENTDUTY = new Clientduty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientdutyRecord> getRecordType() {
        return ClientdutyRecord.class;
    }

    /**
     * The column <code>sales.clientduty.clientid</code>.
     */
    public final TableField<ClientdutyRecord, Long> CLIENTID = createField(DSL.name("clientid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>sales.clientduty.clientname</code>.
     */
    public final TableField<ClientdutyRecord, String> CLIENTNAME = createField(DSL.name("clientname"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>sales.clientduty.number</code>.
     */
    public final TableField<ClientdutyRecord, String> NUMBER = createField(DSL.name("number"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sales.clientduty.duty</code>.
     */
    public final TableField<ClientdutyRecord, Double> DUTY = createField(DSL.name("duty"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>sales.clientduty.data</code>.
     */
    public final TableField<ClientdutyRecord, LocalDate> DATA = createField(DSL.name("data"), SQLDataType.LOCALDATE, this, "");

    private Clientduty(Name alias, Table<ClientdutyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Clientduty(Name alias, Table<ClientdutyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.clientduty</code> table reference
     */
    public Clientduty(String alias) {
        this(DSL.name(alias), CLIENTDUTY);
    }

    /**
     * Create an aliased <code>sales.clientduty</code> table reference
     */
    public Clientduty(Name alias) {
        this(alias, CLIENTDUTY);
    }

    /**
     * Create a <code>sales.clientduty</code> table reference
     */
    public Clientduty() {
        this(DSL.name("clientduty"), null);
    }

    public <O extends Record> Clientduty(Table<O> path, ForeignKey<O, ClientdutyRecord> childPath, InverseForeignKey<O, ClientdutyRecord> parentPath) {
        super(path, childPath, parentPath, CLIENTDUTY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClientdutyPath extends Clientduty implements Path<ClientdutyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClientdutyPath(Table<O> path, ForeignKey<O, ClientdutyRecord> childPath, InverseForeignKey<O, ClientdutyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClientdutyPath(Name alias, Table<ClientdutyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClientdutyPath as(String alias) {
            return new ClientdutyPath(DSL.name(alias), this);
        }

        @Override
        public ClientdutyPath as(Name alias) {
            return new ClientdutyPath(alias, this);
        }

        @Override
        public ClientdutyPath as(Table<?> alias) {
            return new ClientdutyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public List<ForeignKey<ClientdutyRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLIENTDUTY__CLIENTDUTY_CLIENT_FK);
    }

    private transient ClientPath _client;

    /**
     * Get the implicit join path to the <code>sales.client</code> table.
     */
    public ClientPath client() {
        if (_client == null)
            _client = new ClientPath(this, Keys.CLIENTDUTY__CLIENTDUTY_CLIENT_FK, null);

        return _client;
    }

    @Override
    public Clientduty as(String alias) {
        return new Clientduty(DSL.name(alias), this);
    }

    @Override
    public Clientduty as(Name alias) {
        return new Clientduty(alias, this);
    }

    @Override
    public Clientduty as(Table<?> alias) {
        return new Clientduty(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Clientduty rename(String name) {
        return new Clientduty(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Clientduty rename(Name name) {
        return new Clientduty(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Clientduty rename(Table<?> name) {
        return new Clientduty(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientduty where(Condition condition) {
        return new Clientduty(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientduty where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientduty where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientduty where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clientduty where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clientduty where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clientduty where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clientduty where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientduty whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clientduty whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, Double, LocalDate> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super String, ? super String, ? super Double, ? super LocalDate, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super String, ? super String, ? super Double, ? super LocalDate, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
