/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Consproduct.ConsproductPath;
import jooqdata.tables.Supplier.SupplierPath;
import jooqdata.tables.records.ConsignmentnoteRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Consignmentnote extends TableImpl<ConsignmentnoteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.consignmentnote</code>
     */
    public static final Consignmentnote CONSIGNMENTNOTE = new Consignmentnote();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConsignmentnoteRecord> getRecordType() {
        return ConsignmentnoteRecord.class;
    }

    /**
     * The column <code>sales.consignmentnote.consignmentid</code>.
     */
    public final TableField<ConsignmentnoteRecord, Integer> CONSIGNMENTID = createField(DSL.name("consignmentid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.consignmentnote.supplierid</code>.
     */
    public final TableField<ConsignmentnoteRecord, Integer> SUPPLIERID = createField(DSL.name("supplierid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.consignmentnote.amount</code>.
     */
    public final TableField<ConsignmentnoteRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>sales.consignmentnote.date</code>.
     */
    public final TableField<ConsignmentnoteRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    private Consignmentnote(Name alias, Table<ConsignmentnoteRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Consignmentnote(Name alias, Table<ConsignmentnoteRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.consignmentnote</code> table reference
     */
    public Consignmentnote(String alias) {
        this(DSL.name(alias), CONSIGNMENTNOTE);
    }

    /**
     * Create an aliased <code>sales.consignmentnote</code> table reference
     */
    public Consignmentnote(Name alias) {
        this(alias, CONSIGNMENTNOTE);
    }

    /**
     * Create a <code>sales.consignmentnote</code> table reference
     */
    public Consignmentnote() {
        this(DSL.name("consignmentnote"), null);
    }

    public <O extends Record> Consignmentnote(Table<O> path, ForeignKey<O, ConsignmentnoteRecord> childPath, InverseForeignKey<O, ConsignmentnoteRecord> parentPath) {
        super(path, childPath, parentPath, CONSIGNMENTNOTE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ConsignmentnotePath extends Consignmentnote implements Path<ConsignmentnoteRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ConsignmentnotePath(Table<O> path, ForeignKey<O, ConsignmentnoteRecord> childPath, InverseForeignKey<O, ConsignmentnoteRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ConsignmentnotePath(Name alias, Table<ConsignmentnoteRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ConsignmentnotePath as(String alias) {
            return new ConsignmentnotePath(DSL.name(alias), this);
        }

        @Override
        public ConsignmentnotePath as(Name alias) {
            return new ConsignmentnotePath(alias, this);
        }

        @Override
        public ConsignmentnotePath as(Table<?> alias) {
            return new ConsignmentnotePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public UniqueKey<ConsignmentnoteRecord> getPrimaryKey() {
        return Keys.CONSIGNMENTNOTE_PK;
    }

    @Override
    public List<ForeignKey<ConsignmentnoteRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSIGNMENTNOTE__CONSIGNMENTNOTE_SUPPLIER_FK);
    }

    private transient SupplierPath _supplier;

    /**
     * Get the implicit join path to the <code>sales.supplier</code> table.
     */
    public SupplierPath supplier() {
        if (_supplier == null)
            _supplier = new SupplierPath(this, Keys.CONSIGNMENTNOTE__CONSIGNMENTNOTE_SUPPLIER_FK, null);

        return _supplier;
    }

    private transient ConsproductPath _consproduct;

    /**
     * Get the implicit to-many join path to the <code>sales.consproduct</code>
     * table
     */
    public ConsproductPath consproduct() {
        if (_consproduct == null)
            _consproduct = new ConsproductPath(this, null, Keys.CONSPRODUCT__CONSPRODUCT_CONSIGNMENTNOTE_FK.getInverseKey());

        return _consproduct;
    }

    @Override
    public Consignmentnote as(String alias) {
        return new Consignmentnote(DSL.name(alias), this);
    }

    @Override
    public Consignmentnote as(Name alias) {
        return new Consignmentnote(alias, this);
    }

    @Override
    public Consignmentnote as(Table<?> alias) {
        return new Consignmentnote(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Consignmentnote rename(String name) {
        return new Consignmentnote(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Consignmentnote rename(Name name) {
        return new Consignmentnote(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Consignmentnote rename(Table<?> name) {
        return new Consignmentnote(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consignmentnote where(Condition condition) {
        return new Consignmentnote(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consignmentnote where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consignmentnote where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consignmentnote where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Consignmentnote where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Consignmentnote where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Consignmentnote where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Consignmentnote where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consignmentnote whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Consignmentnote whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, BigDecimal, LocalDate> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super Integer, ? super BigDecimal, ? super LocalDate, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super Integer, ? super BigDecimal, ? super LocalDate, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
