/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.DishSetItem.DishSetItemPath;
import jooqdata.tables.records.DishSetRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DishSet extends TableImpl<DishSetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.dish_set</code>
     */
    public static final DishSet DISH_SET = new DishSet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DishSetRecord> getRecordType() {
        return DishSetRecord.class;
    }

    /**
     * The column <code>sales.dish_set.setid</code>.
     */
    public final TableField<DishSetRecord, Integer> SETID = createField(DSL.name("setid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sales.dish_set.setname</code>.
     */
    public final TableField<DishSetRecord, String> SETNAME = createField(DSL.name("setname"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>sales.dish_set.price</code>.
     */
    public final TableField<DishSetRecord, Double> PRICE = createField(DSL.name("price"), SQLDataType.DOUBLE.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>sales.dish_set.first_cost</code>.
     */
    public final TableField<DishSetRecord, Double> FIRST_COST = createField(DSL.name("first_cost"), SQLDataType.DOUBLE.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>sales.dish_set.image_url</code>.
     */
    public final TableField<DishSetRecord, String> IMAGE_URL = createField(DSL.name("image_url"), SQLDataType.VARCHAR(1000), this, "");

    private DishSet(Name alias, Table<DishSetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DishSet(Name alias, Table<DishSetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.dish_set</code> table reference
     */
    public DishSet(String alias) {
        this(DSL.name(alias), DISH_SET);
    }

    /**
     * Create an aliased <code>sales.dish_set</code> table reference
     */
    public DishSet(Name alias) {
        this(alias, DISH_SET);
    }

    /**
     * Create a <code>sales.dish_set</code> table reference
     */
    public DishSet() {
        this(DSL.name("dish_set"), null);
    }

    public <O extends Record> DishSet(Table<O> path, ForeignKey<O, DishSetRecord> childPath, InverseForeignKey<O, DishSetRecord> parentPath) {
        super(path, childPath, parentPath, DISH_SET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DishSetPath extends DishSet implements Path<DishSetRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DishSetPath(Table<O> path, ForeignKey<O, DishSetRecord> childPath, InverseForeignKey<O, DishSetRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DishSetPath(Name alias, Table<DishSetRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DishSetPath as(String alias) {
            return new DishSetPath(DSL.name(alias), this);
        }

        @Override
        public DishSetPath as(Name alias) {
            return new DishSetPath(alias, this);
        }

        @Override
        public DishSetPath as(Table<?> alias) {
            return new DishSetPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public Identity<DishSetRecord, Integer> getIdentity() {
        return (Identity<DishSetRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DishSetRecord> getPrimaryKey() {
        return Keys.DISH_SET_PKEY;
    }

    private transient DishSetItemPath _dishSetItem;

    /**
     * Get the implicit to-many join path to the
     * <code>sales.dish_set_item</code> table
     */
    public DishSetItemPath dishSetItem() {
        if (_dishSetItem == null)
            _dishSetItem = new DishSetItemPath(this, null, Keys.DISH_SET_ITEM__DISH_SET_ITEM_SET_FK.getInverseKey());

        return _dishSetItem;
    }

    @Override
    public List<Check<DishSetRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("dish_set_first_cost_nonnegative_chk"), "((first_cost >= (0)::double precision))", true),
            Internal.createCheck(this, DSL.name("dish_set_price_nonnegative_chk"), "((price >= (0)::double precision))", true)
        );
    }

    @Override
    public DishSet as(String alias) {
        return new DishSet(DSL.name(alias), this);
    }

    @Override
    public DishSet as(Name alias) {
        return new DishSet(alias, this);
    }

    @Override
    public DishSet as(Table<?> alias) {
        return new DishSet(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DishSet rename(String name) {
        return new DishSet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DishSet rename(Name name) {
        return new DishSet(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DishSet rename(Table<?> name) {
        return new DishSet(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishSet where(Condition condition) {
        return new DishSet(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishSet where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishSet where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishSet where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DishSet where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DishSet where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DishSet where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DishSet where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishSet whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishSet whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Double, Double, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Integer, ? super String, ? super Double, ? super Double, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Integer, ? super String, ? super Double, ? super Double, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
