/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Dish.DishPath;
import jooqdata.tables.records.DishCategoryRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DishCategory extends TableImpl<DishCategoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.dish_category</code>
     */
    public static final DishCategory DISH_CATEGORY = new DishCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DishCategoryRecord> getRecordType() {
        return DishCategoryRecord.class;
    }

    /**
     * The column <code>sales.dish_category.category_id</code>.
     */
    public final TableField<DishCategoryRecord, Integer> CATEGORY_ID = createField(DSL.name("category_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sales.dish_category.name</code>.
     */
    public final TableField<DishCategoryRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>sales.dish_category.created_at</code>.
     */
    public final TableField<DishCategoryRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private DishCategory(Name alias, Table<DishCategoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DishCategory(Name alias, Table<DishCategoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.dish_category</code> table reference
     */
    public DishCategory(String alias) {
        this(DSL.name(alias), DISH_CATEGORY);
    }

    /**
     * Create an aliased <code>sales.dish_category</code> table reference
     */
    public DishCategory(Name alias) {
        this(alias, DISH_CATEGORY);
    }

    /**
     * Create a <code>sales.dish_category</code> table reference
     */
    public DishCategory() {
        this(DSL.name("dish_category"), null);
    }

    public <O extends Record> DishCategory(Table<O> path, ForeignKey<O, DishCategoryRecord> childPath, InverseForeignKey<O, DishCategoryRecord> parentPath) {
        super(path, childPath, parentPath, DISH_CATEGORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DishCategoryPath extends DishCategory implements Path<DishCategoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DishCategoryPath(Table<O> path, ForeignKey<O, DishCategoryRecord> childPath, InverseForeignKey<O, DishCategoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DishCategoryPath(Name alias, Table<DishCategoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DishCategoryPath as(String alias) {
            return new DishCategoryPath(DSL.name(alias), this);
        }

        @Override
        public DishCategoryPath as(Name alias) {
            return new DishCategoryPath(alias, this);
        }

        @Override
        public DishCategoryPath as(Table<?> alias) {
            return new DishCategoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public Identity<DishCategoryRecord, Integer> getIdentity() {
        return (Identity<DishCategoryRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DishCategoryRecord> getPrimaryKey() {
        return Keys.DISH_CATEGORY_PKEY;
    }

    @Override
    public List<UniqueKey<DishCategoryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.DISH_CATEGORY_NAME_KEY);
    }

    private transient DishPath _dish;

    /**
     * Get the implicit to-many join path to the <code>sales.dish</code> table
     */
    public DishPath dish() {
        if (_dish == null)
            _dish = new DishPath(this, null, Keys.DISH__DISH_CATEGORY_FK.getInverseKey());

        return _dish;
    }

    @Override
    public DishCategory as(String alias) {
        return new DishCategory(DSL.name(alias), this);
    }

    @Override
    public DishCategory as(Name alias) {
        return new DishCategory(alias, this);
    }

    @Override
    public DishCategory as(Table<?> alias) {
        return new DishCategory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DishCategory rename(String name) {
        return new DishCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DishCategory rename(Name name) {
        return new DishCategory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DishCategory rename(Table<?> name) {
        return new DishCategory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishCategory where(Condition condition) {
        return new DishCategory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishCategory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishCategory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishCategory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DishCategory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DishCategory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DishCategory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DishCategory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishCategory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DishCategory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super String, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
