/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.InventoryDocuments.InventoryDocumentsPath;
import jooqdata.tables.Product.ProductPath;
import jooqdata.tables.records.InventoryDocumentLinesRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InventoryDocumentLines extends TableImpl<InventoryDocumentLinesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.inventory_document_lines</code>
     */
    public static final InventoryDocumentLines INVENTORY_DOCUMENT_LINES = new InventoryDocumentLines();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InventoryDocumentLinesRecord> getRecordType() {
        return InventoryDocumentLinesRecord.class;
    }

    /**
     * The column <code>sales.inventory_document_lines.id</code>.
     */
    public final TableField<InventoryDocumentLinesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sales.inventory_document_lines.document_id</code>.
     */
    public final TableField<InventoryDocumentLinesRecord, Integer> DOCUMENT_ID = createField(DSL.name("document_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.inventory_document_lines.product_id</code>.
     */
    public final TableField<InventoryDocumentLinesRecord, Integer> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.inventory_document_lines.qty</code>.
     */
    public final TableField<InventoryDocumentLinesRecord, BigDecimal> QTY = createField(DSL.name("qty"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>sales.inventory_document_lines.unit_price</code>.
     */
    public final TableField<InventoryDocumentLinesRecord, BigDecimal> UNIT_PRICE = createField(DSL.name("unit_price"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>sales.inventory_document_lines.line_total</code>.
     */
    public final TableField<InventoryDocumentLinesRecord, BigDecimal> LINE_TOTAL = createField(DSL.name("line_total"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>sales.inventory_document_lines.batch_ref</code>.
     */
    public final TableField<InventoryDocumentLinesRecord, String> BATCH_REF = createField(DSL.name("batch_ref"), SQLDataType.VARCHAR, this, "");

    private InventoryDocumentLines(Name alias, Table<InventoryDocumentLinesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InventoryDocumentLines(Name alias, Table<InventoryDocumentLinesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.inventory_document_lines</code> table
     * reference
     */
    public InventoryDocumentLines(String alias) {
        this(DSL.name(alias), INVENTORY_DOCUMENT_LINES);
    }

    /**
     * Create an aliased <code>sales.inventory_document_lines</code> table
     * reference
     */
    public InventoryDocumentLines(Name alias) {
        this(alias, INVENTORY_DOCUMENT_LINES);
    }

    /**
     * Create a <code>sales.inventory_document_lines</code> table reference
     */
    public InventoryDocumentLines() {
        this(DSL.name("inventory_document_lines"), null);
    }

    public <O extends Record> InventoryDocumentLines(Table<O> path, ForeignKey<O, InventoryDocumentLinesRecord> childPath, InverseForeignKey<O, InventoryDocumentLinesRecord> parentPath) {
        super(path, childPath, parentPath, INVENTORY_DOCUMENT_LINES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InventoryDocumentLinesPath extends InventoryDocumentLines implements Path<InventoryDocumentLinesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InventoryDocumentLinesPath(Table<O> path, ForeignKey<O, InventoryDocumentLinesRecord> childPath, InverseForeignKey<O, InventoryDocumentLinesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InventoryDocumentLinesPath(Name alias, Table<InventoryDocumentLinesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InventoryDocumentLinesPath as(String alias) {
            return new InventoryDocumentLinesPath(DSL.name(alias), this);
        }

        @Override
        public InventoryDocumentLinesPath as(Name alias) {
            return new InventoryDocumentLinesPath(alias, this);
        }

        @Override
        public InventoryDocumentLinesPath as(Table<?> alias) {
            return new InventoryDocumentLinesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public Identity<InventoryDocumentLinesRecord, Integer> getIdentity() {
        return (Identity<InventoryDocumentLinesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<InventoryDocumentLinesRecord> getPrimaryKey() {
        return Keys.INVENTORY_DOCUMENT_LINES_PK;
    }

    @Override
    public List<ForeignKey<InventoryDocumentLinesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.INVENTORY_DOCUMENT_LINES__INVENTORY_DOCUMENT_LINES_INVENTORY_DOCUMENTS_FK, Keys.INVENTORY_DOCUMENT_LINES__INVENTORY_DOCUMENT_LINES_PRODUCT_FK);
    }

    private transient InventoryDocumentsPath _inventoryDocuments;

    /**
     * Get the implicit join path to the <code>sales.inventory_documents</code>
     * table.
     */
    public InventoryDocumentsPath inventoryDocuments() {
        if (_inventoryDocuments == null)
            _inventoryDocuments = new InventoryDocumentsPath(this, Keys.INVENTORY_DOCUMENT_LINES__INVENTORY_DOCUMENT_LINES_INVENTORY_DOCUMENTS_FK, null);

        return _inventoryDocuments;
    }

    private transient ProductPath _product;

    /**
     * Get the implicit join path to the <code>sales.product</code> table.
     */
    public ProductPath product() {
        if (_product == null)
            _product = new ProductPath(this, Keys.INVENTORY_DOCUMENT_LINES__INVENTORY_DOCUMENT_LINES_PRODUCT_FK, null);

        return _product;
    }

    @Override
    public InventoryDocumentLines as(String alias) {
        return new InventoryDocumentLines(DSL.name(alias), this);
    }

    @Override
    public InventoryDocumentLines as(Name alias) {
        return new InventoryDocumentLines(alias, this);
    }

    @Override
    public InventoryDocumentLines as(Table<?> alias) {
        return new InventoryDocumentLines(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryDocumentLines rename(String name) {
        return new InventoryDocumentLines(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryDocumentLines rename(Name name) {
        return new InventoryDocumentLines(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InventoryDocumentLines rename(Table<?> name) {
        return new InventoryDocumentLines(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryDocumentLines where(Condition condition) {
        return new InventoryDocumentLines(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryDocumentLines where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryDocumentLines where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryDocumentLines where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryDocumentLines where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryDocumentLines where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryDocumentLines where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InventoryDocumentLines where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryDocumentLines whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InventoryDocumentLines whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Integer, ? super Integer, ? super Integer, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Integer, ? super Integer, ? super Integer, ? super BigDecimal, ? super BigDecimal, ? super BigDecimal, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
