/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.time.LocalDate;
import java.util.Collection;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Orderdish.OrderdishPath;
import jooqdata.tables.records.OrderRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Order extends TableImpl<OrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.order</code>
     */
    public static final Order ORDER = new Order();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderRecord> getRecordType() {
        return OrderRecord.class;
    }

    /**
     * The column <code>sales.order.shiftid</code>.
     */
    public final TableField<OrderRecord, Integer> SHIFTID = createField(DSL.name("shiftid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.order.Date</code>.
     */
    public final TableField<OrderRecord, LocalDate> DATE = createField(DSL.name("Date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>sales.order.clientid</code>.
     */
    public final TableField<OrderRecord, Integer> CLIENTID = createField(DSL.name("clientid"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sales.order.amount</code>.
     */
    public final TableField<OrderRecord, Double> AMOUNT = createField(DSL.name("amount"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>sales.order.status</code>.
     */
    public final TableField<OrderRecord, Boolean> STATUS = createField(DSL.name("status"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>sales.order.orderid</code>.
     */
    public final TableField<OrderRecord, Integer> ORDERID = createField(DSL.name("orderid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sales.order.type</code>.
     */
    public final TableField<OrderRecord, Boolean> TYPE = createField(DSL.name("type"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private Order(Name alias, Table<OrderRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Order(Name alias, Table<OrderRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.order</code> table reference
     */
    public Order(String alias) {
        this(DSL.name(alias), ORDER);
    }

    /**
     * Create an aliased <code>sales.order</code> table reference
     */
    public Order(Name alias) {
        this(alias, ORDER);
    }

    /**
     * Create a <code>sales.order</code> table reference
     */
    public Order() {
        this(DSL.name("order"), null);
    }

    public <O extends Record> Order(Table<O> path, ForeignKey<O, OrderRecord> childPath, InverseForeignKey<O, OrderRecord> parentPath) {
        super(path, childPath, parentPath, ORDER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrderPath extends Order implements Path<OrderRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrderPath(Table<O> path, ForeignKey<O, OrderRecord> childPath, InverseForeignKey<O, OrderRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrderPath(Name alias, Table<OrderRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrderPath as(String alias) {
            return new OrderPath(DSL.name(alias), this);
        }

        @Override
        public OrderPath as(Name alias) {
            return new OrderPath(alias, this);
        }

        @Override
        public OrderPath as(Table<?> alias) {
            return new OrderPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public Identity<OrderRecord, Integer> getIdentity() {
        return (Identity<OrderRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrderRecord> getPrimaryKey() {
        return Keys.ORDER_PK;
    }

    private transient OrderdishPath _orderdish;

    /**
     * Get the implicit to-many join path to the <code>sales.orderdish</code>
     * table
     */
    public OrderdishPath orderdish() {
        if (_orderdish == null)
            _orderdish = new OrderdishPath(this, null, Keys.ORDERDISH__ORDERDISH_ORDER_FK.getInverseKey());

        return _orderdish;
    }

    @Override
    public Order as(String alias) {
        return new Order(DSL.name(alias), this);
    }

    @Override
    public Order as(Name alias) {
        return new Order(alias, this);
    }

    @Override
    public Order as(Table<?> alias) {
        return new Order(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Order rename(String name) {
        return new Order(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Order rename(Name name) {
        return new Order(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Order rename(Table<?> name) {
        return new Order(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Order where(Condition condition) {
        return new Order(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Order where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Order where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Order where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Order where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Order where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Order where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Order where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Order whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Order whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, LocalDate, Integer, Double, Boolean, Integer, Boolean> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Integer, ? super LocalDate, ? super Integer, ? super Double, ? super Boolean, ? super Integer, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Integer, ? super LocalDate, ? super Integer, ? super Double, ? super Boolean, ? super Integer, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
