/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Dish.DishPath;
import jooqdata.tables.Order.OrderPath;
import jooqdata.tables.records.OrderdishRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Orderdish extends TableImpl<OrderdishRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.orderdish</code>
     */
    public static final Orderdish ORDERDISH = new Orderdish();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderdishRecord> getRecordType() {
        return OrderdishRecord.class;
    }

    /**
     * The column <code>sales.orderdish.id</code>.
     */
    public final TableField<OrderdishRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sales.orderdish.orderid</code>.
     */
    public final TableField<OrderdishRecord, Integer> ORDERID = createField(DSL.name("orderid"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sales.orderdish.dishid</code>.
     */
    public final TableField<OrderdishRecord, Integer> DISHID = createField(DSL.name("dishid"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sales.orderdish.qty</code>.
     */
    public final TableField<OrderdishRecord, Integer> QTY = createField(DSL.name("qty"), SQLDataType.INTEGER.nullable(false), this, "");

    private Orderdish(Name alias, Table<OrderdishRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Orderdish(Name alias, Table<OrderdishRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.orderdish</code> table reference
     */
    public Orderdish(String alias) {
        this(DSL.name(alias), ORDERDISH);
    }

    /**
     * Create an aliased <code>sales.orderdish</code> table reference
     */
    public Orderdish(Name alias) {
        this(alias, ORDERDISH);
    }

    /**
     * Create a <code>sales.orderdish</code> table reference
     */
    public Orderdish() {
        this(DSL.name("orderdish"), null);
    }

    public <O extends Record> Orderdish(Table<O> path, ForeignKey<O, OrderdishRecord> childPath, InverseForeignKey<O, OrderdishRecord> parentPath) {
        super(path, childPath, parentPath, ORDERDISH);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrderdishPath extends Orderdish implements Path<OrderdishRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrderdishPath(Table<O> path, ForeignKey<O, OrderdishRecord> childPath, InverseForeignKey<O, OrderdishRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrderdishPath(Name alias, Table<OrderdishRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrderdishPath as(String alias) {
            return new OrderdishPath(DSL.name(alias), this);
        }

        @Override
        public OrderdishPath as(Name alias) {
            return new OrderdishPath(alias, this);
        }

        @Override
        public OrderdishPath as(Table<?> alias) {
            return new OrderdishPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public Identity<OrderdishRecord, Integer> getIdentity() {
        return (Identity<OrderdishRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrderdishRecord> getPrimaryKey() {
        return Keys.NEWTABLE_PK;
    }

    @Override
    public List<ForeignKey<OrderdishRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ORDERDISH__ORDERDISH_ORDER_FK, Keys.ORDERDISH__ORDERDISH_DISH_FK);
    }

    private transient OrderPath _order;

    /**
     * Get the implicit join path to the <code>sales.order</code> table.
     */
    public OrderPath order() {
        if (_order == null)
            _order = new OrderPath(this, Keys.ORDERDISH__ORDERDISH_ORDER_FK, null);

        return _order;
    }

    private transient DishPath _dish;

    /**
     * Get the implicit join path to the <code>sales.dish</code> table.
     */
    public DishPath dish() {
        if (_dish == null)
            _dish = new DishPath(this, Keys.ORDERDISH__ORDERDISH_DISH_FK, null);

        return _dish;
    }

    @Override
    public Orderdish as(String alias) {
        return new Orderdish(DSL.name(alias), this);
    }

    @Override
    public Orderdish as(Name alias) {
        return new Orderdish(alias, this);
    }

    @Override
    public Orderdish as(Table<?> alias) {
        return new Orderdish(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Orderdish rename(String name) {
        return new Orderdish(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Orderdish rename(Name name) {
        return new Orderdish(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Orderdish rename(Table<?> name) {
        return new Orderdish(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orderdish where(Condition condition) {
        return new Orderdish(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orderdish where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orderdish where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orderdish where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orderdish where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orderdish where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orderdish where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orderdish where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orderdish whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orderdish whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
