/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Indexes;
import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Preparation.PreparationPath;
import jooqdata.tables.Warehouse.WarehousePath;
import jooqdata.tables.records.PreparationwarehouseRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Preparationwarehouse extends TableImpl<PreparationwarehouseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.preparationwarehouse</code>
     */
    public static final Preparationwarehouse PREPARATIONWAREHOUSE = new Preparationwarehouse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PreparationwarehouseRecord> getRecordType() {
        return PreparationwarehouseRecord.class;
    }

    /**
     * The column <code>sales.preparationwarehouse.warehouseid</code>.
     */
    public final TableField<PreparationwarehouseRecord, Integer> WAREHOUSEID = createField(DSL.name("warehouseid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.preparationwarehouse.preparationid</code>.
     */
    public final TableField<PreparationwarehouseRecord, Integer> PREPARATIONID = createField(DSL.name("preparationid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>sales.preparationwarehouse.preparationwarehouseid</code>.
     */
    public final TableField<PreparationwarehouseRecord, Integer> PREPARATIONWAREHOUSEID = createField(DSL.name("preparationwarehouseid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sales.preparationwarehouse.quantity</code>.
     */
    public final TableField<PreparationwarehouseRecord, Double> QUANTITY = createField(DSL.name("quantity"), SQLDataType.DOUBLE.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DOUBLE)), this, "");

    private Preparationwarehouse(Name alias, Table<PreparationwarehouseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Preparationwarehouse(Name alias, Table<PreparationwarehouseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.preparationwarehouse</code> table reference
     */
    public Preparationwarehouse(String alias) {
        this(DSL.name(alias), PREPARATIONWAREHOUSE);
    }

    /**
     * Create an aliased <code>sales.preparationwarehouse</code> table reference
     */
    public Preparationwarehouse(Name alias) {
        this(alias, PREPARATIONWAREHOUSE);
    }

    /**
     * Create a <code>sales.preparationwarehouse</code> table reference
     */
    public Preparationwarehouse() {
        this(DSL.name("preparationwarehouse"), null);
    }

    public <O extends Record> Preparationwarehouse(Table<O> path, ForeignKey<O, PreparationwarehouseRecord> childPath, InverseForeignKey<O, PreparationwarehouseRecord> parentPath) {
        super(path, childPath, parentPath, PREPARATIONWAREHOUSE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PreparationwarehousePath extends Preparationwarehouse implements Path<PreparationwarehouseRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PreparationwarehousePath(Table<O> path, ForeignKey<O, PreparationwarehouseRecord> childPath, InverseForeignKey<O, PreparationwarehouseRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PreparationwarehousePath(Name alias, Table<PreparationwarehouseRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PreparationwarehousePath as(String alias) {
            return new PreparationwarehousePath(DSL.name(alias), this);
        }

        @Override
        public PreparationwarehousePath as(Name alias) {
            return new PreparationwarehousePath(alias, this);
        }

        @Override
        public PreparationwarehousePath as(Table<?> alias) {
            return new PreparationwarehousePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PREPARATIONWAREHOUSE_PREP_IDX, Indexes.PREPARATIONWAREHOUSE_WH_IDX);
    }

    @Override
    public Identity<PreparationwarehouseRecord, Integer> getIdentity() {
        return (Identity<PreparationwarehouseRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PreparationwarehouseRecord> getPrimaryKey() {
        return Keys.PREPARATIONWAREHOUSE_PKEY;
    }

    @Override
    public List<ForeignKey<PreparationwarehouseRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PREPARATIONWAREHOUSE__PREPARATIONWAREHOUSE_WAREHOUSE_FK, Keys.PREPARATIONWAREHOUSE__PREPARATIONWAREHOUSE_PREPARATION_FK);
    }

    private transient WarehousePath _warehouse;

    /**
     * Get the implicit join path to the <code>sales.warehouse</code> table.
     */
    public WarehousePath warehouse() {
        if (_warehouse == null)
            _warehouse = new WarehousePath(this, Keys.PREPARATIONWAREHOUSE__PREPARATIONWAREHOUSE_WAREHOUSE_FK, null);

        return _warehouse;
    }

    private transient PreparationPath _preparation;

    /**
     * Get the implicit join path to the <code>sales.preparation</code> table.
     */
    public PreparationPath preparation() {
        if (_preparation == null)
            _preparation = new PreparationPath(this, Keys.PREPARATIONWAREHOUSE__PREPARATIONWAREHOUSE_PREPARATION_FK, null);

        return _preparation;
    }

    @Override
    public List<Check<PreparationwarehouseRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("preparationwarehouse_quantity_nonnegative_chk"), "((quantity >= (0)::double precision))", true)
        );
    }

    @Override
    public Preparationwarehouse as(String alias) {
        return new Preparationwarehouse(DSL.name(alias), this);
    }

    @Override
    public Preparationwarehouse as(Name alias) {
        return new Preparationwarehouse(alias, this);
    }

    @Override
    public Preparationwarehouse as(Table<?> alias) {
        return new Preparationwarehouse(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Preparationwarehouse rename(String name) {
        return new Preparationwarehouse(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Preparationwarehouse rename(Name name) {
        return new Preparationwarehouse(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Preparationwarehouse rename(Table<?> name) {
        return new Preparationwarehouse(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparationwarehouse where(Condition condition) {
        return new Preparationwarehouse(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparationwarehouse where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparationwarehouse where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparationwarehouse where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Preparationwarehouse where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Preparationwarehouse where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Preparationwarehouse where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Preparationwarehouse where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparationwarehouse whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparationwarehouse whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super Integer, ? super Integer, ? super Double, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super Integer, ? super Integer, ? super Double, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
