/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Preparationwarehouse.PreparationwarehousePath;
import jooqdata.tables.Techproduct.TechproductPath;
import jooqdata.tables.records.PreparationRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Preparation extends TableImpl<PreparationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.preparation</code>
     */
    public static final Preparation PREPARATION = new Preparation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PreparationRecord> getRecordType() {
        return PreparationRecord.class;
    }

    /**
     * The column <code>sales.preparation.preparationid</code>.
     */
    public final TableField<PreparationRecord, Integer> PREPARATIONID = createField(DSL.name("preparationid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sales.preparation.preparationname</code>.
     */
    public final TableField<PreparationRecord, String> PREPARATIONNAME = createField(DSL.name("preparationname"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>sales.preparation.output_weight</code>.
     */
    public final TableField<PreparationRecord, Double> OUTPUT_WEIGHT = createField(DSL.name("output_weight"), SQLDataType.DOUBLE.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.DOUBLE)), this, "");

    private Preparation(Name alias, Table<PreparationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Preparation(Name alias, Table<PreparationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.preparation</code> table reference
     */
    public Preparation(String alias) {
        this(DSL.name(alias), PREPARATION);
    }

    /**
     * Create an aliased <code>sales.preparation</code> table reference
     */
    public Preparation(Name alias) {
        this(alias, PREPARATION);
    }

    /**
     * Create a <code>sales.preparation</code> table reference
     */
    public Preparation() {
        this(DSL.name("preparation"), null);
    }

    public <O extends Record> Preparation(Table<O> path, ForeignKey<O, PreparationRecord> childPath, InverseForeignKey<O, PreparationRecord> parentPath) {
        super(path, childPath, parentPath, PREPARATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PreparationPath extends Preparation implements Path<PreparationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PreparationPath(Table<O> path, ForeignKey<O, PreparationRecord> childPath, InverseForeignKey<O, PreparationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PreparationPath(Name alias, Table<PreparationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PreparationPath as(String alias) {
            return new PreparationPath(DSL.name(alias), this);
        }

        @Override
        public PreparationPath as(Name alias) {
            return new PreparationPath(alias, this);
        }

        @Override
        public PreparationPath as(Table<?> alias) {
            return new PreparationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public Identity<PreparationRecord, Integer> getIdentity() {
        return (Identity<PreparationRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<PreparationRecord> getPrimaryKey() {
        return Keys.PREPARATION_PKEY;
    }

    private transient PreparationwarehousePath _preparationwarehouse;

    /**
     * Get the implicit to-many join path to the
     * <code>sales.preparationwarehouse</code> table
     */
    public PreparationwarehousePath preparationwarehouse() {
        if (_preparationwarehouse == null)
            _preparationwarehouse = new PreparationwarehousePath(this, null, Keys.PREPARATIONWAREHOUSE__PREPARATIONWAREHOUSE_PREPARATION_FK.getInverseKey());

        return _preparationwarehouse;
    }

    private transient TechproductPath _techproductIngredientPreparationFk;

    /**
     * Get the implicit to-many join path to the <code>sales.techproduct</code>
     * table, via the <code>techproduct_ingredient_preparation_fk</code> key
     */
    public TechproductPath techproductIngredientPreparationFk() {
        if (_techproductIngredientPreparationFk == null)
            _techproductIngredientPreparationFk = new TechproductPath(this, null, Keys.TECHPRODUCT__TECHPRODUCT_INGREDIENT_PREPARATION_FK.getInverseKey());

        return _techproductIngredientPreparationFk;
    }

    private transient TechproductPath _techproductPreparationOwnerFk;

    /**
     * Get the implicit to-many join path to the <code>sales.techproduct</code>
     * table, via the <code>techproduct_preparation_owner_fk</code> key
     */
    public TechproductPath techproductPreparationOwnerFk() {
        if (_techproductPreparationOwnerFk == null)
            _techproductPreparationOwnerFk = new TechproductPath(this, null, Keys.TECHPRODUCT__TECHPRODUCT_PREPARATION_OWNER_FK.getInverseKey());

        return _techproductPreparationOwnerFk;
    }

    @Override
    public List<Check<PreparationRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("preparation_output_weight_positive_chk"), "((output_weight > (0)::double precision))", true)
        );
    }

    @Override
    public Preparation as(String alias) {
        return new Preparation(DSL.name(alias), this);
    }

    @Override
    public Preparation as(Name alias) {
        return new Preparation(alias, this);
    }

    @Override
    public Preparation as(Table<?> alias) {
        return new Preparation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Preparation rename(String name) {
        return new Preparation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Preparation rename(Name name) {
        return new Preparation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Preparation rename(Table<?> name) {
        return new Preparation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparation where(Condition condition) {
        return new Preparation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Preparation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Preparation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Preparation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Preparation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Preparation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super String, ? super Double, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super String, ? super Double, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
