/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Consproduct.ConsproductPath;
import jooqdata.tables.Productwarehouse.ProductwarehousePath;
import jooqdata.tables.Supplier.SupplierPath;
import jooqdata.tables.Techproduct.TechproductPath;
import jooqdata.tables.records.ProductRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Product extends TableImpl<ProductRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.product</code>
     */
    public static final Product PRODUCT = new Product();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductRecord> getRecordType() {
        return ProductRecord.class;
    }

    /**
     * The column <code>sales.product.supplierid</code>.
     */
    public final TableField<ProductRecord, Integer> SUPPLIERID = createField(DSL.name("supplierid"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sales.product.productname</code>.
     */
    public final TableField<ProductRecord, String> PRODUCTNAME = createField(DSL.name("productname"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>sales.product.productprice</code>.
     */
    public final TableField<ProductRecord, BigDecimal> PRODUCTPRICE = createField(DSL.name("productprice"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>sales.product.waste</code>.
     */
    public final TableField<ProductRecord, Double> WASTE = createField(DSL.name("waste"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>sales.product.isfavourite</code>.
     */
    public final TableField<ProductRecord, Boolean> ISFAVOURITE = createField(DSL.name("isfavourite"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>sales.product.productid</code>.
     */
    public final TableField<ProductRecord, Integer> PRODUCTID = createField(DSL.name("productid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    private Product(Name alias, Table<ProductRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Product(Name alias, Table<ProductRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.product</code> table reference
     */
    public Product(String alias) {
        this(DSL.name(alias), PRODUCT);
    }

    /**
     * Create an aliased <code>sales.product</code> table reference
     */
    public Product(Name alias) {
        this(alias, PRODUCT);
    }

    /**
     * Create a <code>sales.product</code> table reference
     */
    public Product() {
        this(DSL.name("product"), null);
    }

    public <O extends Record> Product(Table<O> path, ForeignKey<O, ProductRecord> childPath, InverseForeignKey<O, ProductRecord> parentPath) {
        super(path, childPath, parentPath, PRODUCT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProductPath extends Product implements Path<ProductRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProductPath(Table<O> path, ForeignKey<O, ProductRecord> childPath, InverseForeignKey<O, ProductRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProductPath(Name alias, Table<ProductRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProductPath as(String alias) {
            return new ProductPath(DSL.name(alias), this);
        }

        @Override
        public ProductPath as(Name alias) {
            return new ProductPath(alias, this);
        }

        @Override
        public ProductPath as(Table<?> alias) {
            return new ProductPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public Identity<ProductRecord, Integer> getIdentity() {
        return (Identity<ProductRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductRecord> getPrimaryKey() {
        return Keys.PRODUCT_PK;
    }

    @Override
    public List<ForeignKey<ProductRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRODUCT__PRODUCT_SUPPLIER_FK);
    }

    private transient SupplierPath _supplier;

    /**
     * Get the implicit join path to the <code>sales.supplier</code> table.
     */
    public SupplierPath supplier() {
        if (_supplier == null)
            _supplier = new SupplierPath(this, Keys.PRODUCT__PRODUCT_SUPPLIER_FK, null);

        return _supplier;
    }

    private transient ConsproductPath _consproduct;

    /**
     * Get the implicit to-many join path to the <code>sales.consproduct</code>
     * table
     */
    public ConsproductPath consproduct() {
        if (_consproduct == null)
            _consproduct = new ConsproductPath(this, null, Keys.CONSPRODUCT__CONSPRODUCT_PRODUCT_FK.getInverseKey());

        return _consproduct;
    }

    private transient ProductwarehousePath _productwarehouse;

    /**
     * Get the implicit to-many join path to the
     * <code>sales.productwarehouse</code> table
     */
    public ProductwarehousePath productwarehouse() {
        if (_productwarehouse == null)
            _productwarehouse = new ProductwarehousePath(this, null, Keys.PRODUCTWAREHOUSE__PRODUCTWAREHOUSEID_PRODUCT_FK.getInverseKey());

        return _productwarehouse;
    }

    private transient TechproductPath _techproduct;

    /**
     * Get the implicit to-many join path to the <code>sales.techproduct</code>
     * table
     */
    public TechproductPath techproduct() {
        if (_techproduct == null)
            _techproduct = new TechproductPath(this, null, Keys.TECHPRODUCT__TECHPRODUCT_PRODUCT_FK.getInverseKey());

        return _techproduct;
    }

    @Override
    public Product as(String alias) {
        return new Product(DSL.name(alias), this);
    }

    @Override
    public Product as(Name alias) {
        return new Product(alias, this);
    }

    @Override
    public Product as(Table<?> alias) {
        return new Product(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(String name) {
        return new Product(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(Name name) {
        return new Product(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(Table<?> name) {
        return new Product(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product where(Condition condition) {
        return new Product(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Product where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Product where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Product where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Product where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Product whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, BigDecimal, Double, Boolean, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Integer, ? super String, ? super BigDecimal, ? super Double, ? super Boolean, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super String, ? super BigDecimal, ? super Double, ? super Boolean, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
