/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Product.ProductPath;
import jooqdata.tables.Warehouse.WarehousePath;
import jooqdata.tables.records.ProductwarehouseRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Productwarehouse extends TableImpl<ProductwarehouseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.productwarehouse</code>
     */
    public static final Productwarehouse PRODUCTWAREHOUSE = new Productwarehouse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductwarehouseRecord> getRecordType() {
        return ProductwarehouseRecord.class;
    }

    /**
     * The column <code>sales.productwarehouse.warehouseid</code>.
     */
    public final TableField<ProductwarehouseRecord, Integer> WAREHOUSEID = createField(DSL.name("warehouseid"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sales.productwarehouse.productid</code>.
     */
    public final TableField<ProductwarehouseRecord, Integer> PRODUCTID = createField(DSL.name("productid"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sales.productwarehouse.productwarehouseid</code>.
     */
    public final TableField<ProductwarehouseRecord, Integer> PRODUCTWAREHOUSEID = createField(DSL.name("productwarehouseid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sales.productwarehouse.quantity</code>.
     */
    public final TableField<ProductwarehouseRecord, Double> QUANTITY = createField(DSL.name("quantity"), SQLDataType.DOUBLE, this, "");

    private Productwarehouse(Name alias, Table<ProductwarehouseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Productwarehouse(Name alias, Table<ProductwarehouseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.productwarehouse</code> table reference
     */
    public Productwarehouse(String alias) {
        this(DSL.name(alias), PRODUCTWAREHOUSE);
    }

    /**
     * Create an aliased <code>sales.productwarehouse</code> table reference
     */
    public Productwarehouse(Name alias) {
        this(alias, PRODUCTWAREHOUSE);
    }

    /**
     * Create a <code>sales.productwarehouse</code> table reference
     */
    public Productwarehouse() {
        this(DSL.name("productwarehouse"), null);
    }

    public <O extends Record> Productwarehouse(Table<O> path, ForeignKey<O, ProductwarehouseRecord> childPath, InverseForeignKey<O, ProductwarehouseRecord> parentPath) {
        super(path, childPath, parentPath, PRODUCTWAREHOUSE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProductwarehousePath extends Productwarehouse implements Path<ProductwarehouseRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProductwarehousePath(Table<O> path, ForeignKey<O, ProductwarehouseRecord> childPath, InverseForeignKey<O, ProductwarehouseRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProductwarehousePath(Name alias, Table<ProductwarehouseRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProductwarehousePath as(String alias) {
            return new ProductwarehousePath(DSL.name(alias), this);
        }

        @Override
        public ProductwarehousePath as(Name alias) {
            return new ProductwarehousePath(alias, this);
        }

        @Override
        public ProductwarehousePath as(Table<?> alias) {
            return new ProductwarehousePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public Identity<ProductwarehouseRecord, Integer> getIdentity() {
        return (Identity<ProductwarehouseRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductwarehouseRecord> getPrimaryKey() {
        return Keys.PRODUCTWAREHOUSE_PK;
    }

    @Override
    public List<ForeignKey<ProductwarehouseRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRODUCTWAREHOUSE__PRODUCTWAREHOUSEID_WAREHOUSE_FK, Keys.PRODUCTWAREHOUSE__PRODUCTWAREHOUSEID_PRODUCT_FK);
    }

    private transient WarehousePath _warehouse;

    /**
     * Get the implicit join path to the <code>sales.warehouse</code> table.
     */
    public WarehousePath warehouse() {
        if (_warehouse == null)
            _warehouse = new WarehousePath(this, Keys.PRODUCTWAREHOUSE__PRODUCTWAREHOUSEID_WAREHOUSE_FK, null);

        return _warehouse;
    }

    private transient ProductPath _product;

    /**
     * Get the implicit join path to the <code>sales.product</code> table.
     */
    public ProductPath product() {
        if (_product == null)
            _product = new ProductPath(this, Keys.PRODUCTWAREHOUSE__PRODUCTWAREHOUSEID_PRODUCT_FK, null);

        return _product;
    }

    @Override
    public Productwarehouse as(String alias) {
        return new Productwarehouse(DSL.name(alias), this);
    }

    @Override
    public Productwarehouse as(Name alias) {
        return new Productwarehouse(alias, this);
    }

    @Override
    public Productwarehouse as(Table<?> alias) {
        return new Productwarehouse(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Productwarehouse rename(String name) {
        return new Productwarehouse(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Productwarehouse rename(Name name) {
        return new Productwarehouse(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Productwarehouse rename(Table<?> name) {
        return new Productwarehouse(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouse where(Condition condition) {
        return new Productwarehouse(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouse where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouse where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouse where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Productwarehouse where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Productwarehouse where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Productwarehouse where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Productwarehouse where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouse whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouse whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super Integer, ? super Integer, ? super Double, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super Integer, ? super Integer, ? super Double, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
