/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Product.ProductPath;
import jooqdata.tables.Warehouse.WarehousePath;
import jooqdata.tables.records.ProductwarehouseidRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Productwarehouseid extends TableImpl<ProductwarehouseidRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.productwarehouseid</code>
     */
    public static final Productwarehouseid PRODUCTWAREHOUSEID = new Productwarehouseid();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductwarehouseidRecord> getRecordType() {
        return ProductwarehouseidRecord.class;
    }

    /**
     * The column <code>sales.productwarehouseid.warehouseid</code>.
     */
    public final TableField<ProductwarehouseidRecord, Integer> WAREHOUSEID = createField(DSL.name("warehouseid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.productwarehouseid.productid</code>.
     */
    public final TableField<ProductwarehouseidRecord, Integer> PRODUCTID = createField(DSL.name("productid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.productwarehouseid.net</code>.
     */
    public final TableField<ProductwarehouseidRecord, Double> NET = createField(DSL.name("net"), SQLDataType.DOUBLE.nullable(false), this, "");

    private Productwarehouseid(Name alias, Table<ProductwarehouseidRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Productwarehouseid(Name alias, Table<ProductwarehouseidRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.productwarehouseid</code> table reference
     */
    public Productwarehouseid(String alias) {
        this(DSL.name(alias), PRODUCTWAREHOUSEID);
    }

    /**
     * Create an aliased <code>sales.productwarehouseid</code> table reference
     */
    public Productwarehouseid(Name alias) {
        this(alias, PRODUCTWAREHOUSEID);
    }

    /**
     * Create a <code>sales.productwarehouseid</code> table reference
     */
    public Productwarehouseid() {
        this(DSL.name("productwarehouseid"), null);
    }

    public <O extends Record> Productwarehouseid(Table<O> path, ForeignKey<O, ProductwarehouseidRecord> childPath, InverseForeignKey<O, ProductwarehouseidRecord> parentPath) {
        super(path, childPath, parentPath, PRODUCTWAREHOUSEID);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProductwarehouseidPath extends Productwarehouseid implements Path<ProductwarehouseidRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProductwarehouseidPath(Table<O> path, ForeignKey<O, ProductwarehouseidRecord> childPath, InverseForeignKey<O, ProductwarehouseidRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProductwarehouseidPath(Name alias, Table<ProductwarehouseidRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProductwarehouseidPath as(String alias) {
            return new ProductwarehouseidPath(DSL.name(alias), this);
        }

        @Override
        public ProductwarehouseidPath as(Name alias) {
            return new ProductwarehouseidPath(alias, this);
        }

        @Override
        public ProductwarehouseidPath as(Table<?> alias) {
            return new ProductwarehouseidPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public List<ForeignKey<ProductwarehouseidRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRODUCTWAREHOUSEID__PRODUCTWAREHOUSEID_WAREHOUSE_FK_1, Keys.PRODUCTWAREHOUSEID__PRODUCTWAREHOUSEID_PRODUCT_FK_1);
    }

    private transient WarehousePath _warehouse;

    /**
     * Get the implicit join path to the <code>sales.warehouse</code> table.
     */
    public WarehousePath warehouse() {
        if (_warehouse == null)
            _warehouse = new WarehousePath(this, Keys.PRODUCTWAREHOUSEID__PRODUCTWAREHOUSEID_WAREHOUSE_FK_1, null);

        return _warehouse;
    }

    private transient ProductPath _product;

    /**
     * Get the implicit join path to the <code>sales.product</code> table.
     */
    public ProductPath product() {
        if (_product == null)
            _product = new ProductPath(this, Keys.PRODUCTWAREHOUSEID__PRODUCTWAREHOUSEID_PRODUCT_FK_1, null);

        return _product;
    }

    @Override
    public Productwarehouseid as(String alias) {
        return new Productwarehouseid(DSL.name(alias), this);
    }

    @Override
    public Productwarehouseid as(Name alias) {
        return new Productwarehouseid(alias, this);
    }

    @Override
    public Productwarehouseid as(Table<?> alias) {
        return new Productwarehouseid(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Productwarehouseid rename(String name) {
        return new Productwarehouseid(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Productwarehouseid rename(Name name) {
        return new Productwarehouseid(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Productwarehouseid rename(Table<?> name) {
        return new Productwarehouseid(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouseid where(Condition condition) {
        return new Productwarehouseid(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouseid where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouseid where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouseid where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Productwarehouseid where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Productwarehouseid where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Productwarehouseid where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Productwarehouseid where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouseid whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Productwarehouseid whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super Integer, ? super Double, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super Integer, ? super Double, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
