/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Person.PersonPath;
import jooqdata.tables.records.ShiftpersonRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Shiftperson extends TableImpl<ShiftpersonRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.shiftperson</code>
     */
    public static final Shiftperson SHIFTPERSON = new Shiftperson();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShiftpersonRecord> getRecordType() {
        return ShiftpersonRecord.class;
    }

    /**
     * The column <code>sales.shiftperson.shiftpersonid</code>.
     */
    public final TableField<ShiftpersonRecord, Integer> SHIFTPERSONID = createField(DSL.name("shiftpersonid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.shiftperson.shiftid</code>.
     */
    public final TableField<ShiftpersonRecord, Integer> SHIFTID = createField(DSL.name("shiftid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.shiftperson.personid</code>.
     */
    public final TableField<ShiftpersonRecord, Integer> PERSONID = createField(DSL.name("personid"), SQLDataType.INTEGER, this, "");

    private Shiftperson(Name alias, Table<ShiftpersonRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Shiftperson(Name alias, Table<ShiftpersonRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.shiftperson</code> table reference
     */
    public Shiftperson(String alias) {
        this(DSL.name(alias), SHIFTPERSON);
    }

    /**
     * Create an aliased <code>sales.shiftperson</code> table reference
     */
    public Shiftperson(Name alias) {
        this(alias, SHIFTPERSON);
    }

    /**
     * Create a <code>sales.shiftperson</code> table reference
     */
    public Shiftperson() {
        this(DSL.name("shiftperson"), null);
    }

    public <O extends Record> Shiftperson(Table<O> path, ForeignKey<O, ShiftpersonRecord> childPath, InverseForeignKey<O, ShiftpersonRecord> parentPath) {
        super(path, childPath, parentPath, SHIFTPERSON);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ShiftpersonPath extends Shiftperson implements Path<ShiftpersonRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ShiftpersonPath(Table<O> path, ForeignKey<O, ShiftpersonRecord> childPath, InverseForeignKey<O, ShiftpersonRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ShiftpersonPath(Name alias, Table<ShiftpersonRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ShiftpersonPath as(String alias) {
            return new ShiftpersonPath(DSL.name(alias), this);
        }

        @Override
        public ShiftpersonPath as(Name alias) {
            return new ShiftpersonPath(alias, this);
        }

        @Override
        public ShiftpersonPath as(Table<?> alias) {
            return new ShiftpersonPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public UniqueKey<ShiftpersonRecord> getPrimaryKey() {
        return Keys.SHIFTPERSON_PK;
    }

    @Override
    public List<ForeignKey<ShiftpersonRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SHIFTPERSON__SHIFTPERSON_PERSON_FK);
    }

    private transient PersonPath _person;

    /**
     * Get the implicit join path to the <code>sales.person</code> table.
     */
    public PersonPath person() {
        if (_person == null)
            _person = new PersonPath(this, Keys.SHIFTPERSON__SHIFTPERSON_PERSON_FK, null);

        return _person;
    }

    @Override
    public Shiftperson as(String alias) {
        return new Shiftperson(DSL.name(alias), this);
    }

    @Override
    public Shiftperson as(Name alias) {
        return new Shiftperson(alias, this);
    }

    @Override
    public Shiftperson as(Table<?> alias) {
        return new Shiftperson(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Shiftperson rename(String name) {
        return new Shiftperson(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Shiftperson rename(Name name) {
        return new Shiftperson(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Shiftperson rename(Table<?> name) {
        return new Shiftperson(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shiftperson where(Condition condition) {
        return new Shiftperson(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shiftperson where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shiftperson where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shiftperson where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shiftperson where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shiftperson where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shiftperson where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Shiftperson where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shiftperson whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Shiftperson whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
