/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Collection;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Consignmentnote.ConsignmentnotePath;
import jooqdata.tables.Favoriteproduct.FavoriteproductPath;
import jooqdata.tables.records.SupplierRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Supplier extends TableImpl<SupplierRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.supplier</code>
     */
    public static final Supplier SUPPLIER = new Supplier();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SupplierRecord> getRecordType() {
        return SupplierRecord.class;
    }

    /**
     * The column <code>sales.supplier.supplierid</code>.
     */
    public final TableField<SupplierRecord, Integer> SUPPLIERID = createField(DSL.name("supplierid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.supplier.suppliername</code>.
     */
    public final TableField<SupplierRecord, String> SUPPLIERNAME = createField(DSL.name("suppliername"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>sales.supplier.communication</code>.
     */
    public final TableField<SupplierRecord, String> COMMUNICATION = createField(DSL.name("communication"), SQLDataType.VARCHAR, this, "");

    private Supplier(Name alias, Table<SupplierRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Supplier(Name alias, Table<SupplierRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.supplier</code> table reference
     */
    public Supplier(String alias) {
        this(DSL.name(alias), SUPPLIER);
    }

    /**
     * Create an aliased <code>sales.supplier</code> table reference
     */
    public Supplier(Name alias) {
        this(alias, SUPPLIER);
    }

    /**
     * Create a <code>sales.supplier</code> table reference
     */
    public Supplier() {
        this(DSL.name("supplier"), null);
    }

    public <O extends Record> Supplier(Table<O> path, ForeignKey<O, SupplierRecord> childPath, InverseForeignKey<O, SupplierRecord> parentPath) {
        super(path, childPath, parentPath, SUPPLIER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SupplierPath extends Supplier implements Path<SupplierRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SupplierPath(Table<O> path, ForeignKey<O, SupplierRecord> childPath, InverseForeignKey<O, SupplierRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SupplierPath(Name alias, Table<SupplierRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SupplierPath as(String alias) {
            return new SupplierPath(DSL.name(alias), this);
        }

        @Override
        public SupplierPath as(Name alias) {
            return new SupplierPath(alias, this);
        }

        @Override
        public SupplierPath as(Table<?> alias) {
            return new SupplierPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public UniqueKey<SupplierRecord> getPrimaryKey() {
        return Keys.SUPPLIER_PK;
    }

    private transient ConsignmentnotePath _consignmentnote;

    /**
     * Get the implicit to-many join path to the
     * <code>sales.consignmentnote</code> table
     */
    public ConsignmentnotePath consignmentnote() {
        if (_consignmentnote == null)
            _consignmentnote = new ConsignmentnotePath(this, null, Keys.CONSIGNMENTNOTE__CONSIGNMENTNOTE_SUPPLIER_FK.getInverseKey());

        return _consignmentnote;
    }

    private transient FavoriteproductPath _favoriteproduct;

    /**
     * Get the implicit to-many join path to the
     * <code>sales.favoriteproduct</code> table
     */
    public FavoriteproductPath favoriteproduct() {
        if (_favoriteproduct == null)
            _favoriteproduct = new FavoriteproductPath(this, null, Keys.FAVORITEPRODUCT__FAVORITEPRODUCT_SUPPLIER_FK.getInverseKey());

        return _favoriteproduct;
    }

    @Override
    public Supplier as(String alias) {
        return new Supplier(DSL.name(alias), this);
    }

    @Override
    public Supplier as(Name alias) {
        return new Supplier(alias, this);
    }

    @Override
    public Supplier as(Table<?> alias) {
        return new Supplier(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Supplier rename(String name) {
        return new Supplier(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Supplier rename(Name name) {
        return new Supplier(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Supplier rename(Table<?> name) {
        return new Supplier(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier where(Condition condition) {
        return new Supplier(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Supplier where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Supplier where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Supplier where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Supplier where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Supplier whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
