/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Indexes;
import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.records.TaxOutboxRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Function14;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Records;
import org.jooq.Row14;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TaxOutbox extends TableImpl<TaxOutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.tax_outbox</code>
     */
    public static final TaxOutbox TAX_OUTBOX = new TaxOutbox();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaxOutboxRecord> getRecordType() {
        return TaxOutboxRecord.class;
    }

    /**
     * The column <code>sales.tax_outbox.id</code>.
     */
    public final TableField<TaxOutboxRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>sales.tax_outbox.aggregate_type</code>.
     */
    public final TableField<TaxOutboxRecord, String> AGGREGATE_TYPE = createField(DSL.name("aggregate_type"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("'order'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sales.tax_outbox.aggregate_id</code>.
     */
    public final TableField<TaxOutboxRecord, Integer> AGGREGATE_ID = createField(DSL.name("aggregate_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.tax_outbox.event_type</code>.
     */
    public final TableField<TaxOutboxRecord, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.VARCHAR(60).nullable(false), this, "");

    /**
     * The column <code>sales.tax_outbox.event_key</code>.
     */
    public final TableField<TaxOutboxRecord, String> EVENT_KEY = createField(DSL.name("event_key"), SQLDataType.VARCHAR(140).nullable(false), this, "");

    /**
     * The column <code>sales.tax_outbox.payload_json</code>.
     */
    public final TableField<TaxOutboxRecord, JSONB> PAYLOAD_JSON = createField(DSL.name("payload_json"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>sales.tax_outbox.status</code>.
     */
    public final TableField<TaxOutboxRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'pending'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>sales.tax_outbox.available_at</code>.
     */
    public final TableField<TaxOutboxRecord, LocalDateTime> AVAILABLE_AT = createField(DSL.name("available_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>sales.tax_outbox.locked_at</code>.
     */
    public final TableField<TaxOutboxRecord, LocalDateTime> LOCKED_AT = createField(DSL.name("locked_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>sales.tax_outbox.processed_at</code>.
     */
    public final TableField<TaxOutboxRecord, LocalDateTime> PROCESSED_AT = createField(DSL.name("processed_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>sales.tax_outbox.attempt_count</code>.
     */
    public final TableField<TaxOutboxRecord, Integer> ATTEMPT_COUNT = createField(DSL.name("attempt_count"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>sales.tax_outbox.last_error</code>.
     */
    public final TableField<TaxOutboxRecord, String> LAST_ERROR = createField(DSL.name("last_error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>sales.tax_outbox.created_at</code>.
     */
    public final TableField<TaxOutboxRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>sales.tax_outbox.updated_at</code>.
     */
    public final TableField<TaxOutboxRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private TaxOutbox(Name alias, Table<TaxOutboxRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TaxOutbox(Name alias, Table<TaxOutboxRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.tax_outbox</code> table reference
     */
    public TaxOutbox(String alias) {
        this(DSL.name(alias), TAX_OUTBOX);
    }

    /**
     * Create an aliased <code>sales.tax_outbox</code> table reference
     */
    public TaxOutbox(Name alias) {
        this(alias, TAX_OUTBOX);
    }

    /**
     * Create a <code>sales.tax_outbox</code> table reference
     */
    public TaxOutbox() {
        this(DSL.name("tax_outbox"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TAX_OUTBOX_AGGREGATE_IDX, Indexes.TAX_OUTBOX_CREATED_IDX, Indexes.TAX_OUTBOX_EVENT_KEY_UQ_IDX, Indexes.TAX_OUTBOX_STATUS_AVAILABLE_IDX);
    }

    @Override
    public Identity<TaxOutboxRecord, Long> getIdentity() {
        return (Identity<TaxOutboxRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TaxOutboxRecord> getPrimaryKey() {
        return Keys.TAX_OUTBOX_PKEY;
    }

    @Override
    public List<Check<TaxOutboxRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("tax_outbox_attempt_nonnegative_chk"), "((attempt_count >= 0))", true),
            Internal.createCheck(this, DSL.name("tax_outbox_status_chk"), "(((status)::text = ANY ((ARRAY['pending'::character varying, 'processing'::character varying, 'processed'::character varying, 'failed'::character varying, 'dead_letter'::character varying])::text[])))", true)
        );
    }

    @Override
    public TaxOutbox as(String alias) {
        return new TaxOutbox(DSL.name(alias), this);
    }

    @Override
    public TaxOutbox as(Name alias) {
        return new TaxOutbox(alias, this);
    }

    @Override
    public TaxOutbox as(Table<?> alias) {
        return new TaxOutbox(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TaxOutbox rename(String name) {
        return new TaxOutbox(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaxOutbox rename(Name name) {
        return new TaxOutbox(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TaxOutbox rename(Table<?> name) {
        return new TaxOutbox(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaxOutbox where(Condition condition) {
        return new TaxOutbox(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaxOutbox where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaxOutbox where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaxOutbox where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaxOutbox where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaxOutbox where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaxOutbox where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TaxOutbox where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaxOutbox whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TaxOutbox whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, String, Integer, String, String, JSONB, String, LocalDateTime, LocalDateTime, LocalDateTime, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function14<? super Long, ? super String, ? super Integer, ? super String, ? super String, ? super JSONB, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? super LocalDateTime, ? super Integer, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function14<? super Long, ? super String, ? super Integer, ? super String, ? super String, ? super JSONB, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? super LocalDateTime, ? super Integer, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
