/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Product.ProductPath;
import jooqdata.tables.records.TechproductRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Techproduct extends TableImpl<TechproductRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.techproduct</code>
     */
    public static final Techproduct TECHPRODUCT = new Techproduct();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TechproductRecord> getRecordType() {
        return TechproductRecord.class;
    }

    /**
     * The column <code>sales.techproduct.techproductid</code>.
     */
    public final TableField<TechproductRecord, Integer> TECHPRODUCTID = createField(DSL.name("techproductid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.techproduct.techproductname</code>.
     */
    public final TableField<TechproductRecord, String> TECHPRODUCTNAME = createField(DSL.name("techproductname"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>sales.techproduct.productid</code>.
     */
    public final TableField<TechproductRecord, Integer> PRODUCTID = createField(DSL.name("productid"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sales.techproduct.waste</code>.
     */
    public final TableField<TechproductRecord, Double> WASTE = createField(DSL.name("waste"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>sales.techproduct.weight</code>.
     */
    public final TableField<TechproductRecord, Double> WEIGHT = createField(DSL.name("weight"), SQLDataType.DOUBLE.nullable(false), this, "");

    private Techproduct(Name alias, Table<TechproductRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Techproduct(Name alias, Table<TechproductRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.techproduct</code> table reference
     */
    public Techproduct(String alias) {
        this(DSL.name(alias), TECHPRODUCT);
    }

    /**
     * Create an aliased <code>sales.techproduct</code> table reference
     */
    public Techproduct(Name alias) {
        this(alias, TECHPRODUCT);
    }

    /**
     * Create a <code>sales.techproduct</code> table reference
     */
    public Techproduct() {
        this(DSL.name("techproduct"), null);
    }

    public <O extends Record> Techproduct(Table<O> path, ForeignKey<O, TechproductRecord> childPath, InverseForeignKey<O, TechproductRecord> parentPath) {
        super(path, childPath, parentPath, TECHPRODUCT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TechproductPath extends Techproduct implements Path<TechproductRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TechproductPath(Table<O> path, ForeignKey<O, TechproductRecord> childPath, InverseForeignKey<O, TechproductRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TechproductPath(Name alias, Table<TechproductRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TechproductPath as(String alias) {
            return new TechproductPath(DSL.name(alias), this);
        }

        @Override
        public TechproductPath as(Name alias) {
            return new TechproductPath(alias, this);
        }

        @Override
        public TechproductPath as(Table<?> alias) {
            return new TechproductPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public UniqueKey<TechproductRecord> getPrimaryKey() {
        return Keys.TECHPRODUCT_PK;
    }

    @Override
    public List<UniqueKey<TechproductRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TECHPRODUCT_UNIQUE);
    }

    @Override
    public List<ForeignKey<TechproductRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TECHPRODUCT__TECHPRODUCT_PRODUCT_FK);
    }

    private transient ProductPath _product;

    /**
     * Get the implicit join path to the <code>sales.product</code> table.
     */
    public ProductPath product() {
        if (_product == null)
            _product = new ProductPath(this, Keys.TECHPRODUCT__TECHPRODUCT_PRODUCT_FK, null);

        return _product;
    }

    @Override
    public Techproduct as(String alias) {
        return new Techproduct(DSL.name(alias), this);
    }

    @Override
    public Techproduct as(Name alias) {
        return new Techproduct(alias, this);
    }

    @Override
    public Techproduct as(Table<?> alias) {
        return new Techproduct(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Techproduct rename(String name) {
        return new Techproduct(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Techproduct rename(Name name) {
        return new Techproduct(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Techproduct rename(Table<?> name) {
        return new Techproduct(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Techproduct where(Condition condition) {
        return new Techproduct(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Techproduct where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Techproduct where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Techproduct where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Techproduct where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Techproduct where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Techproduct where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Techproduct where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Techproduct whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Techproduct whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, Double, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Integer, ? super String, ? super Integer, ? super Double, ? super Double, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Integer, ? super String, ? super Integer, ? super Double, ? super Double, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
