/*
 * This file is generated by jOOQ.
 */
package jooqdata.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.function.Function;

import jooqdata.Keys;
import jooqdata.Sales;
import jooqdata.tables.Productwarehouse.ProductwarehousePath;
import jooqdata.tables.records.WarehouseRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.SelectField;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Warehouse extends TableImpl<WarehouseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales.warehouse</code>
     */
    public static final Warehouse WAREHOUSE = new Warehouse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WarehouseRecord> getRecordType() {
        return WarehouseRecord.class;
    }

    /**
     * The column <code>sales.warehouse.warehousename</code>.
     */
    public final TableField<WarehouseRecord, String> WAREHOUSENAME = createField(DSL.name("warehousename"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>sales.warehouse.warehouseid</code>.
     */
    public final TableField<WarehouseRecord, Integer> WAREHOUSEID = createField(DSL.name("warehouseid"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    private Warehouse(Name alias, Table<WarehouseRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Warehouse(Name alias, Table<WarehouseRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>sales.warehouse</code> table reference
     */
    public Warehouse(String alias) {
        this(DSL.name(alias), WAREHOUSE);
    }

    /**
     * Create an aliased <code>sales.warehouse</code> table reference
     */
    public Warehouse(Name alias) {
        this(alias, WAREHOUSE);
    }

    /**
     * Create a <code>sales.warehouse</code> table reference
     */
    public Warehouse() {
        this(DSL.name("warehouse"), null);
    }

    public <O extends Record> Warehouse(Table<O> path, ForeignKey<O, WarehouseRecord> childPath, InverseForeignKey<O, WarehouseRecord> parentPath) {
        super(path, childPath, parentPath, WAREHOUSE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WarehousePath extends Warehouse implements Path<WarehouseRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WarehousePath(Table<O> path, ForeignKey<O, WarehouseRecord> childPath, InverseForeignKey<O, WarehouseRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WarehousePath(Name alias, Table<WarehouseRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WarehousePath as(String alias) {
            return new WarehousePath(DSL.name(alias), this);
        }

        @Override
        public WarehousePath as(Name alias) {
            return new WarehousePath(alias, this);
        }

        @Override
        public WarehousePath as(Table<?> alias) {
            return new WarehousePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sales.SALES;
    }

    @Override
    public Identity<WarehouseRecord, Integer> getIdentity() {
        return (Identity<WarehouseRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WarehouseRecord> getPrimaryKey() {
        return Keys.WAREHOUSE_PK;
    }

    @Override
    public List<UniqueKey<WarehouseRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.WAREHOUSE_UNIQUE);
    }

    private transient ProductwarehousePath _productwarehouse;

    /**
     * Get the implicit to-many join path to the
     * <code>sales.productwarehouse</code> table
     */
    public ProductwarehousePath productwarehouse() {
        if (_productwarehouse == null)
            _productwarehouse = new ProductwarehousePath(this, null, Keys.PRODUCTWAREHOUSE__PRODUCTWAREHOUSEID_WAREHOUSE_FK.getInverseKey());

        return _productwarehouse;
    }

    @Override
    public Warehouse as(String alias) {
        return new Warehouse(DSL.name(alias), this);
    }

    @Override
    public Warehouse as(Name alias) {
        return new Warehouse(alias, this);
    }

    @Override
    public Warehouse as(Table<?> alias) {
        return new Warehouse(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Warehouse rename(String name) {
        return new Warehouse(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Warehouse rename(Name name) {
        return new Warehouse(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Warehouse rename(Table<?> name) {
        return new Warehouse(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse where(Condition condition) {
        return new Warehouse(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Warehouse where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Warehouse where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Warehouse where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Warehouse where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Warehouse whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
