/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import jooqdata.tables.Consignmentnote;
import jooqdata.tables.Consproduct;
import jooqdata.tables.Dish;
import jooqdata.tables.Favoriteproduct;
import jooqdata.tables.Person;
import jooqdata.tables.Product;
import jooqdata.tables.Shift;
import jooqdata.tables.Shiftperson;
import jooqdata.tables.Supplier;
import jooqdata.tables.Techproduct;
import jooqdata.tables.Warehouse;
import jooqdata.tables.records.ConsignmentnoteRecord;
import jooqdata.tables.records.ConsproductRecord;
import jooqdata.tables.records.DishRecord;
import jooqdata.tables.records.FavoriteproductRecord;
import jooqdata.tables.records.PersonRecord;
import jooqdata.tables.records.ProductRecord;
import jooqdata.tables.records.ShiftRecord;
import jooqdata.tables.records.ShiftpersonRecord;
import jooqdata.tables.records.SupplierRecord;
import jooqdata.tables.records.TechproductRecord;
import jooqdata.tables.records.WarehouseRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * sales.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ConsignmentnoteRecord> CONSIGNMENTNOTE_PK = Internal.createUniqueKey(Consignmentnote.CONSIGNMENTNOTE, DSL.name("consignmentnote_pk"), new TableField[] { Consignmentnote.CONSIGNMENTNOTE.CONSIGNMENTID }, true);
    public static final UniqueKey<DishRecord> DISH_PK = Internal.createUniqueKey(Dish.DISH, DSL.name("dish_pk"), new TableField[] { Dish.DISH.DISHID }, true);
    public static final UniqueKey<FavoriteproductRecord> FAVORITEPRODUCT_PK = Internal.createUniqueKey(Favoriteproduct.FAVORITEPRODUCT, DSL.name("favoriteproduct_pk"), new TableField[] { Favoriteproduct.FAVORITEPRODUCT.ID }, true);
    public static final UniqueKey<PersonRecord> PERSON_PK = Internal.createUniqueKey(Person.PERSON, DSL.name("person_pk"), new TableField[] { Person.PERSON.PERSONID }, true);
    public static final UniqueKey<ProductRecord> PRODUCT_PK = Internal.createUniqueKey(Product.PRODUCT, DSL.name("product_pk"), new TableField[] { Product.PRODUCT.PRODUCTID }, true);
    public static final UniqueKey<ShiftRecord> SHIFT_PK = Internal.createUniqueKey(Shift.SHIFT, DSL.name("shift_pk"), new TableField[] { Shift.SHIFT.SHIFTID }, true);
    public static final UniqueKey<ShiftpersonRecord> SHIFTPERSON_PK = Internal.createUniqueKey(Shiftperson.SHIFTPERSON, DSL.name("shiftperson_pk"), new TableField[] { Shiftperson.SHIFTPERSON.SHIFTPERSONID }, true);
    public static final UniqueKey<SupplierRecord> SUPPLIER_PK = Internal.createUniqueKey(Supplier.SUPPLIER, DSL.name("supplier_pk"), new TableField[] { Supplier.SUPPLIER.SUPPLIERID }, true);
    public static final UniqueKey<TechproductRecord> TECHPRODUCT_PK = Internal.createUniqueKey(Techproduct.TECHPRODUCT, DSL.name("techproduct_pk"), new TableField[] { Techproduct.TECHPRODUCT.TECHPRODUCTID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ConsignmentnoteRecord, SupplierRecord> CONSIGNMENTNOTE__CONSIGNMENTNOTE_SUPPLIER_FK = Internal.createForeignKey(Consignmentnote.CONSIGNMENTNOTE, DSL.name("consignmentnote_supplier_fk"), new TableField[] { Consignmentnote.CONSIGNMENTNOTE.SUPPLIERID }, Keys.SUPPLIER_PK, new TableField[] { Supplier.SUPPLIER.SUPPLIERID }, true);
    public static final ForeignKey<ConsproductRecord, ConsignmentnoteRecord> CONSPRODUCT__CONSPRODUCT_CONSIGNMENTNOTE_FK = Internal.createForeignKey(Consproduct.CONSPRODUCT, DSL.name("consproduct_consignmentnote_fk"), new TableField[] { Consproduct.CONSPRODUCT.CONSIGNMENTID }, Keys.CONSIGNMENTNOTE_PK, new TableField[] { Consignmentnote.CONSIGNMENTNOTE.CONSIGNMENTID }, true);
    public static final ForeignKey<ConsproductRecord, ProductRecord> CONSPRODUCT__CONSPRODUCT_PRODUCT_FK = Internal.createForeignKey(Consproduct.CONSPRODUCT, DSL.name("consproduct_product_fk"), new TableField[] { Consproduct.CONSPRODUCT.PRODUCTID }, Keys.PRODUCT_PK, new TableField[] { Product.PRODUCT.PRODUCTID }, true);
    public static final ForeignKey<FavoriteproductRecord, SupplierRecord> FAVORITEPRODUCT__FAVORITEPRODUCT_SUPPLIER_FK = Internal.createForeignKey(Favoriteproduct.FAVORITEPRODUCT, DSL.name("favoriteproduct_supplier_fk"), new TableField[] { Favoriteproduct.FAVORITEPRODUCT.SUPPLIERID }, Keys.SUPPLIER_PK, new TableField[] { Supplier.SUPPLIER.SUPPLIERID }, true);
    public static final ForeignKey<ShiftpersonRecord, PersonRecord> SHIFTPERSON__SHIFTPERSON_PERSON_FK = Internal.createForeignKey(Shiftperson.SHIFTPERSON, DSL.name("shiftperson_person_fk"), new TableField[] { Shiftperson.SHIFTPERSON.PERSONID }, Keys.PERSON_PK, new TableField[] { Person.PERSON.PERSONID }, true);
    public static final ForeignKey<ShiftpersonRecord, ShiftRecord> SHIFTPERSON__SHIFTPERSON_SHIFT_FK = Internal.createForeignKey(Shiftperson.SHIFTPERSON, DSL.name("shiftperson_shift_fk"), new TableField[] { Shiftperson.SHIFTPERSON.SHIFTID }, Keys.SHIFT_PK, new TableField[] { Shift.SHIFT.SHIFTID }, true);
    public static final ForeignKey<TechproductRecord, ProductRecord> TECHPRODUCT__TECHPRODUCT_PRODUCT_FK = Internal.createForeignKey(Techproduct.TECHPRODUCT, DSL.name("techproduct_product_fk"), new TableField[] { Techproduct.TECHPRODUCT.PRODUCTID }, Keys.PRODUCT_PK, new TableField[] { Product.PRODUCT.PRODUCTID }, true);
    public static final ForeignKey<WarehouseRecord, ProductRecord> WAREHOUSE__WAREHOUSE_PRODUCT_FK = Internal.createForeignKey(Warehouse.WAREHOUSE, DSL.name("warehouse_product_fk"), new TableField[] { Warehouse.WAREHOUSE.PRODUCTID }, Keys.PRODUCT_PK, new TableField[] { Product.PRODUCT.PRODUCTID }, true);
}
