/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import java.util.Arrays;
import java.util.List;

import jooqdata.tables.Client;
import jooqdata.tables.Clientdish;
import jooqdata.tables.Consignmentnote;
import jooqdata.tables.Consproduct;
import jooqdata.tables.Dish;
import jooqdata.tables.Favoriteproduct;
import jooqdata.tables.Order;
import jooqdata.tables.Person;
import jooqdata.tables.Product;
import jooqdata.tables.Productwarehouseid;
import jooqdata.tables.Shift;
import jooqdata.tables.Shiftperson;
import jooqdata.tables.Supplier;
import jooqdata.tables.Techproduct;
import jooqdata.tables.Warehouse;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sales extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales</code>
     */
    public static final Sales SALES = new Sales();

    /**
     * The table <code>sales.client</code>.
     */
    public final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>sales.clientdish</code>.
     */
    public final Clientdish CLIENTDISH = Clientdish.CLIENTDISH;

    /**
     * The table <code>sales.consignmentnote</code>.
     */
    public final Consignmentnote CONSIGNMENTNOTE = Consignmentnote.CONSIGNMENTNOTE;

    /**
     * The table <code>sales.consproduct</code>.
     */
    public final Consproduct CONSPRODUCT = Consproduct.CONSPRODUCT;

    /**
     * The table <code>sales.dish</code>.
     */
    public final Dish DISH = Dish.DISH;

    /**
     * The table <code>sales.favoriteproduct</code>.
     */
    public final Favoriteproduct FAVORITEPRODUCT = Favoriteproduct.FAVORITEPRODUCT;

    /**
     * The table <code>sales.order</code>.
     */
    public final Order ORDER = Order.ORDER;

    /**
     * The table <code>sales.person</code>.
     */
    public final Person PERSON = Person.PERSON;

    /**
     * The table <code>sales.product</code>.
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>sales.productwarehouseid</code>.
     */
    public final Productwarehouseid PRODUCTWAREHOUSEID = Productwarehouseid.PRODUCTWAREHOUSEID;

    /**
     * The table <code>sales.shift</code>.
     */
    public final Shift SHIFT = Shift.SHIFT;

    /**
     * The table <code>sales.shiftperson</code>.
     */
    public final Shiftperson SHIFTPERSON = Shiftperson.SHIFTPERSON;

    /**
     * The table <code>sales.supplier</code>.
     */
    public final Supplier SUPPLIER = Supplier.SUPPLIER;

    /**
     * The table <code>sales.techproduct</code>.
     */
    public final Techproduct TECHPRODUCT = Techproduct.TECHPRODUCT;

    /**
     * The table <code>sales.warehouse</code>.
     */
    public final Warehouse WAREHOUSE = Warehouse.WAREHOUSE;

    /**
     * No further instances allowed
     */
    private Sales() {
        super("sales", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Client.CLIENT,
            Clientdish.CLIENTDISH,
            Consignmentnote.CONSIGNMENTNOTE,
            Consproduct.CONSPRODUCT,
            Dish.DISH,
            Favoriteproduct.FAVORITEPRODUCT,
            Order.ORDER,
            Person.PERSON,
            Product.PRODUCT,
            Productwarehouseid.PRODUCTWAREHOUSEID,
            Shift.SHIFT,
            Shiftperson.SHIFTPERSON,
            Supplier.SUPPLIER,
            Techproduct.TECHPRODUCT,
            Warehouse.WAREHOUSE
        );
    }
}
