/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import java.util.Arrays;
import java.util.List;

import jooqdata.tables.Client;
import jooqdata.tables.Clientdish;
import jooqdata.tables.Clientduty;
import jooqdata.tables.Consignmentnote;
import jooqdata.tables.Consproduct;
import jooqdata.tables.Dish;
import jooqdata.tables.InventoryDocumentLines;
import jooqdata.tables.InventoryDocuments;
import jooqdata.tables.Order;
import jooqdata.tables.Orderdish;
import jooqdata.tables.Person;
import jooqdata.tables.Product;
import jooqdata.tables.Productwarehouse;
import jooqdata.tables.Shift;
import jooqdata.tables.Shiftperson;
import jooqdata.tables.StockMovements;
import jooqdata.tables.Supplier;
import jooqdata.tables.SupplierPriceHistory;
import jooqdata.tables.Techproduct;
import jooqdata.tables.Warehouse;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sales extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sales</code>
     */
    public static final Sales SALES = new Sales();

    /**
     * The table <code>sales.client</code>.
     */
    public final Client CLIENT = Client.CLIENT;

    /**
     * The table <code>sales.clientdish</code>.
     */
    public final Clientdish CLIENTDISH = Clientdish.CLIENTDISH;

    /**
     * The table <code>sales.clientduty</code>.
     */
    public final Clientduty CLIENTDUTY = Clientduty.CLIENTDUTY;

    /**
     * The table <code>sales.consignmentnote</code>.
     */
    public final Consignmentnote CONSIGNMENTNOTE = Consignmentnote.CONSIGNMENTNOTE;

    /**
     * The table <code>sales.consproduct</code>.
     */
    public final Consproduct CONSPRODUCT = Consproduct.CONSPRODUCT;

    /**
     * The table <code>sales.dish</code>.
     */
    public final Dish DISH = Dish.DISH;

    /**
     * The table <code>sales.inventory_document_lines</code>.
     */
    public final InventoryDocumentLines INVENTORY_DOCUMENT_LINES = InventoryDocumentLines.INVENTORY_DOCUMENT_LINES;

    /**
     * The table <code>sales.inventory_documents</code>.
     */
    public final InventoryDocuments INVENTORY_DOCUMENTS = InventoryDocuments.INVENTORY_DOCUMENTS;

    /**
     * The table <code>sales.order</code>.
     */
    public final Order ORDER = Order.ORDER;

    /**
     * The table <code>sales.orderdish</code>.
     */
    public final Orderdish ORDERDISH = Orderdish.ORDERDISH;

    /**
     * The table <code>sales.person</code>.
     */
    public final Person PERSON = Person.PERSON;

    /**
     * The table <code>sales.product</code>.
     */
    public final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>sales.productwarehouse</code>.
     */
    public final Productwarehouse PRODUCTWAREHOUSE = Productwarehouse.PRODUCTWAREHOUSE;

    /**
     * The table <code>sales.shift</code>.
     */
    public final Shift SHIFT = Shift.SHIFT;

    /**
     * The table <code>sales.shiftperson</code>.
     */
    public final Shiftperson SHIFTPERSON = Shiftperson.SHIFTPERSON;

    /**
     * The table <code>sales.stock_movements</code>.
     */
    public final StockMovements STOCK_MOVEMENTS = StockMovements.STOCK_MOVEMENTS;

    /**
     * The table <code>sales.supplier</code>.
     */
    public final Supplier SUPPLIER = Supplier.SUPPLIER;

    /**
     * The table <code>sales.supplier_price_history</code>.
     */
    public final SupplierPriceHistory SUPPLIER_PRICE_HISTORY = SupplierPriceHistory.SUPPLIER_PRICE_HISTORY;

    /**
     * The table <code>sales.techproduct</code>.
     */
    public final Techproduct TECHPRODUCT = Techproduct.TECHPRODUCT;

    /**
     * The table <code>sales.warehouse</code>.
     */
    public final Warehouse WAREHOUSE = Warehouse.WAREHOUSE;

    /**
     * No further instances allowed
     */
    private Sales() {
        super("sales", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Client.CLIENT,
            Clientdish.CLIENTDISH,
            Clientduty.CLIENTDUTY,
            Consignmentnote.CONSIGNMENTNOTE,
            Consproduct.CONSPRODUCT,
            Dish.DISH,
            InventoryDocumentLines.INVENTORY_DOCUMENT_LINES,
            InventoryDocuments.INVENTORY_DOCUMENTS,
            Order.ORDER,
            Orderdish.ORDERDISH,
            Person.PERSON,
            Product.PRODUCT,
            Productwarehouse.PRODUCTWAREHOUSE,
            Shift.SHIFT,
            Shiftperson.SHIFTPERSON,
            StockMovements.STOCK_MOVEMENTS,
            Supplier.SUPPLIER,
            SupplierPriceHistory.SUPPLIER_PRICE_HISTORY,
            Techproduct.TECHPRODUCT,
            Warehouse.WAREHOUSE
        );
    }
}
